Fedorov_lab24
Maxsmile123/MAI_109B_22 pull request #124
Opened 2023-06-05 16:49 UTC by hedgefo9

2023-06-07 20:57 UTC, Maxsmile123 requested changes

2023-06-07 20:57 UTC, Maxsmile123 commented on Fedorov/lab24/include/Deque.hpp
Заинклудь из 26-ой, а отсюда убери

2023-06-07 20:57 UTC, Maxsmile123 commented on Fedorov/lab24/include/Iterator.hpp
Аналогично, как в дэке

2023-06-07 20:57 UTC, Maxsmile123 commented on Fedorov/lab24/include/Node.hpp
> +    T data;
Только тут оно вряд ли темлейт. Это же дерево выражений - тут чар, вероятно. Иначе, это просто нода для бинарного дерева, которую можно было заинклудить

2023-06-07 20:57 UTC, Maxsmile123 commented on Fedorov/lab24/src/Deque.cpp
> +    return NULL;
хм... Я б возвращал дефолтный конструтор тогда б: ```T()```

2023-06-07 20:57 UTC, Maxsmile123 commented on Fedorov/lab24/src/ExpressionTree.cpp
> +void ExpressionTree::print_postfix_expr(Node<char> *curr_node) const {
почему не const Node*?

2023-06-07 20:57 UTC, Maxsmile123 commented on Fedorov/lab24/src/ExpressionTree.cpp
> +void ExpressionTree::print_infix_expr(Node<char> *curr_node) const {
почему не const Node*?

2023-06-07 20:57 UTC, Maxsmile123 commented on Fedorov/lab24/src/ExpressionTree.cpp
> +void ExpressionTree::delete_branch(Node<char> *curr_node) {
почему не const Node*?

2023-06-07 20:57 UTC, Maxsmile123 commented on Fedorov/lab24/src/ExpressionTree.cpp
> +void ExpressionTree::print_tree(Node<char> *curr_node, const size_t &height) const {
почему не const Node*?

2023-06-07 21:06 UTC, hedgefo9 commented on Fedorov/lab24/include/Node.hpp
> +    T data;
Просто в эту ноду я ещё добавил создание рекурсивной копии поддерева, т.е. функцию get_copy(), это нужно для задания в лабе. Окей, могу убрать шаблоны и сделать char, чтобы это была Node только для дерева выражений. В 26 лабе это было бы нелогично добавлять, т.к. там это не нужно. Дек постараюсь заинлудить из 26 лабы и ничего не сломать))

2023-06-07 21:11 UTC, hedgefo9 commented on Fedorov/lab24/src/Deque.cpp
> +    return NULL;
Я вот не знал что возвращать в таком случае, только вот это пришло в голову. Это перекочевало из 26 лабы, а дек я собираюсь инклудить оттуда после исправлений, так что хз как исправить. Если нужно, могу создать ПР отдельно для правки в 26 лабу в Deque.

2023-06-15 21:38 UTC, hedgefo9 commented on Fedorov/lab24/include/Deque.hpp
исправил

2023-06-15 21:39 UTC, hedgefo9 commented on Fedorov/lab24/include/Iterator.hpp
поправил

2023-06-15 21:39 UTC, hedgefo9 commented on Fedorov/lab24/src/ExpressionTree.cpp
> +void ExpressionTree::print_postfix_expr(Node<char> *curr_node) const {
исправил

2023-06-15 21:39 UTC, hedgefo9 commented on Fedorov/lab24/src/ExpressionTree.cpp
> +void ExpressionTree::print_infix_expr(Node<char> *curr_node) const {
исправил

2023-06-15 21:39 UTC, hedgefo9 commented on Fedorov/lab24/src/ExpressionTree.cpp
> +void ExpressionTree::delete_branch(Node<char> *curr_node) {
исправил

2023-06-15 21:39 UTC, hedgefo9 commented on Fedorov/lab24/src/ExpressionTree.cpp
> +void ExpressionTree::print_tree(Node<char> *curr_node, const size_t &height) const {
исправил

2023-06-18 13:45 UTC, Maxsmile123 approved these changes

2023-06-18 13:45 UTC, Maxsmile123 commented on Fedorov/lab24/include/ExpressionTree.hpp
> +    void print_tree(const TreeNode *curr_node, const size_t &height = 0) const;
Убери префикс трее. Что ещё будет печатать объект типа ExpressionTree ?)
И вообще это лучше через перегрузку операторов выполнить, но да ладно

2023-06-18 13:45 UTC, Maxsmile123 commented on Fedorov/lab24/include/ExpressionTree.hpp
> +    void print_postfix_expr(const TreeNode *curr_node) const;
Можно сделать одну функцию, которая в зависимости о параметра печатает определённую форму:
```void print_expr(const TreeNode *curr_node, bool is_postfix = false) const;```
Но да ладно

2023-06-18 13:45 UTC, merged