21 лаба
Maxsmile123/MAI_109B_22 pull request #13
Opened 2023-03-07 10:19 UTC by BaronPipistron

21 лаба

2023-03-07 17:56 UTC, Maxsmile123 requested changes

2023-03-07 17:56 UTC, Maxsmile123 commented on Kontsebalov/lab21/Lab21.bash
> +files_list=$(sudo find / -path "/run" -prune -o -type f -name "${prefix}*" -printf "%s %p\n"|sort -n -r)
Название скорее уж list_of_files. Да и то непонятно, что это за абстрактные файлы

2023-03-07 17:56 UTC, Maxsmile123 commented on Kontsebalov/lab21/Lab21.bash
> +count_files=$(echo "$files_list"|wc -l)
Тут тоже. number_of_flies скорее?

2023-03-07 17:56 UTC, Maxsmile123 commented on Kontsebalov/lab21/Lab21.py
> +            elif file.startswith(prefix) is None:
А это зачем? У нас либо да, либо нет. Если нет, ничего не трогаем. Кажется, это нужно поправить. Лишняя проверка

2023-03-07 17:56 UTC, Maxsmile123 commented on Kontsebalov/lab21/Lab21.py
> +    if len(files_list) == 0:
По секрету, только между нами...
Проверка на пустой список выглядит так:
if not files_list:

2023-03-07 17:56 UTC, Maxsmile123 commented on Kontsebalov/lab21/Lab21.py
> +        files_size -= os.path.getsize(os.path.join(root, file_delete))
У тебя дублируется код: os.path.join()
Давай вынесем это в отдельную переменную и будет использовать её

2023-03-07 18:21 UTC, BaronPipistron commented
Фиксы

2023-03-09 02:38 UTC, Maxsmile123 approved these changes
Мне ок

2023-03-09 02:39 UTC, merged