24lab
Maxsmile123/MAI_109B_22 pull request #134
Opened 2023-06-14 19:41 UTC by willr4in

2023-06-15 08:59 UTC, Maxsmile123 requested changes
Не хватает файла с запуском дерева и изменения файла, где будет прописано задание

2023-06-15 08:59 UTC, Maxsmile123 commented on Shambilov/lab24/src/ExpressionTree.cpp
> +bool isOperator(char c) {
Разве это все операторы? Я знаю ещё +, / как минимум

2023-06-15 08:59 UTC, Maxsmile123 commented on Shambilov/lab24/src/ExpressionTree.cpp
> +void ExpressionTree::printTree(Node* root, const size_t height) const {
Tree из названия стоит убрать. Понятно, что объект ExpressionTree печатет именно дерево, а не что-то другое. И вообще это лучше сделать через перегрузку оператора

2023-06-15 08:59 UTC, Maxsmile123 commented on Shambilov/lab24/src/ExpressionTree.cpp
> +void ExpressionTree::deleteTree(Node* node) {
Лучше назвать это clear

2023-06-15 08:59 UTC, Maxsmile123 commented on Shambilov/lab24/src/ExpressionTree.cpp
> +    delete node;
Надо бы ещё node в nullptr привести, ибо после этой функции у тебя объект потенциально ещё на стеке лежит

2023-06-15 08:59 UTC, Maxsmile123 commented on Shambilov/lab24/src/ExpressionTree.cpp
> +Node* ExpressionTree::createTree(const std::string& postfix) {
Tree из названия убери

2023-06-15 08:59 UTC, Maxsmile123 commented on Shambilov/lab24/src/ExpressionTree.cpp
> +Node* ExpressionTree::createTree(const std::string& postfix) {
И почему оно не void? Создание дерева по подразумевает возвращение чего-либо. У объекта есть корень, который и представляет собой дерево

2023-06-15 08:59 UTC, Maxsmile123 commented on Shambilov/lab24/src/ExpressionTree.cpp
> +Node* ExpressionTree::newNode(char data) {
Зачем нужно это, если есть конструктор Node от char?

2023-06-15 08:59 UTC, Maxsmile123 commented on Shambilov/lab24/include/Node.hpp
> +    Node(const char data);
explicit

2023-06-15 08:59 UTC, Maxsmile123 commented on Shambilov/lab24/src/Stack.cpp
> +    for (T elem: list){
В цикле нужно проходить по const&, иначе ты копии создаёшь

2023-06-21 23:23 UTC, willr4in commented on Shambilov/lab24/src/Stack.cpp
> +    for (T elem: list){
Так я же прохожу по ссылке листа, а элементы мне уж точно надо брать отдельно каждый и кидать в стэк, иначе я не понимаю

2023-06-22 12:57 UTC, Maxsmile123 commented on Shambilov/lab24/src/Stack.cpp
> +    for (T elem: list){
```for (const& T elem: list)```

2023-06-22 12:58 UTC, Maxsmile123 requested changes

2023-06-22 12:58 UTC, Maxsmile123 commented on Shambilov/lab24/src/ExpressionTree.cpp
> +    node = nullptr;
Словил утечку. Сначала удалить, потом привести к nullptr

2023-06-23 18:18 UTC, willr4in commented
готово

2023-06-25 19:03 UTC, merged