Kp8
Maxsmile123/MAI_109B_22 pull request #135
Opened 2023-06-14 19:46 UTC by willr4in

2023-06-15 09:19 UTC, Maxsmile123 requested changes
Добавь файл с запуском кода и вариант задания

2023-06-15 09:19 UTC, Maxsmile123 commented on Shambilov/KP8/include/Iterator.hpp
> +class List;
Зачем это, если ты выше этот список заинклудил?

2023-06-15 09:19 UTC, Maxsmile123 commented on Shambilov/KP8/include/Iterator.hpp
> +    friend class List<T>;
Это не нужно. Список не должен иметь доступа к полю, ибо всё взаимодействие с этим полем происходит через методы итератора

2023-06-15 09:19 UTC, Maxsmile123 commented on Shambilov/KP8/include/Node.hpp
> +    node(const T& = T(), node<T>* = nullptr);
Тут не помешает гетер.

2023-06-15 09:19 UTC, Maxsmile123 commented on Shambilov/KP8/include/Node.hpp
> +class node {
Название класса с большой буквы

2023-06-15 09:19 UTC, Maxsmile123 commented on Shambilov/KP8/include/Iterator.hpp
> +class iterator {
Название класса с большой буквы

2023-06-15 09:19 UTC, Maxsmile123 commented on Shambilov/KP8/src/Iterator.cpp
> +#include "../include/Node.hpp"
Зачем тут это, если это уже прописано в хедере?

2023-06-15 09:19 UTC, Maxsmile123 commented on Shambilov/KP8/src/Iterator.cpp
> +        ++returnIterator;
Что если size больше, чем длина списка? Ты получишь сигфолт

2023-06-15 09:19 UTC, Maxsmile123 commented on Shambilov/KP8/src/List.cpp
> +        delete deleteNode;
А указатели в nullptr? На эту ноду же может кто-то указывать

2023-06-15 09:19 UTC, Maxsmile123 commented on Shambilov/KP8/src/List.cpp
> +    ++eraseIt;
Получается, ты ноду start не удаляешь. Это неверно

2023-06-25 10:22 UTC, willr4in commented on Shambilov/KP8/include/Node.hpp
> +    node(const T& = T(), node<T>* = nullptr);
get_data()?

2023-06-25 19:03 UTC, merged