Kp9
Maxsmile123/MAI_109B_22 pull request #136
Opened 2023-06-14 19:50 UTC by willr4in

2023-06-18 13:53 UTC, Maxsmile123 requested changes

2023-06-18 13:53 UTC, Maxsmile123 commented on Shambilov/KP9/include/Table.hpp
> +    void sortOfKhoar();
Пользователю действительно нужно знать, что там под капотом Хоар?)
Давай просто sort

2023-06-18 13:53 UTC, Maxsmile123 commented on Shambilov/KP9/src/Table.cpp
> +int Table<T>::partition(int start, int end) {
Если я суну start = -100, то получу что-то приятно?)
Может, ограничить пользователя, сказав, что мы используем size_t?

2023-06-18 13:53 UTC, Maxsmile123 commented on Shambilov/KP9/src/Table.cpp
> +    int i = start - 1;
Имеет смысл все int заменить на size_t

2023-06-21 16:56 UTC, willr4in commented
произошел фикс

2023-06-22 13:01 UTC, Maxsmile123 requested changes

2023-06-22 13:01 UTC, Maxsmile123 commented on Shambilov/KP9/src/Table.cpp
> +    myVector<int> indexes;
size_t

2023-06-25 19:04 UTC, Maxsmile123 approved these changes

2023-06-25 19:04 UTC, merged