Kp8
Maxsmile123/MAI_109B_22 pull request #138
Opened 2023-06-16 21:46 UTC by Dots109

2023-06-18 14:14 UTC, Maxsmile123 requested changes

2023-06-18 14:14 UTC, Maxsmile123 commented on Nedosekin/KP8/src/Iterator.cpp
> +Iterator<T>::Iterator(Node<T> *node)
const

2023-06-18 14:14 UTC, Maxsmile123 commented on Nedosekin/KP8/src/Iterator.cpp
> +bool Iterator<T>::operator==(Iterator<T> left) const
Принимаем по const&

2023-06-18 14:14 UTC, Maxsmile123 commented on Nedosekin/KP8/src/Iterator.cpp
> +bool Iterator<T>::operator!=(Iterator<T> left) const
const&

2023-06-18 14:14 UTC, Maxsmile123 commented on Nedosekin/KP8/src/List.cpp
> +        while (currentNode.node_ != nullptr) {
Не злоупотребляй дружбой... Итератор можно разыменовать, списку не нужен доступ к приватным полям итератора

2023-06-18 14:14 UTC, Maxsmile123 commented on Nedosekin/KP8/src/List.cpp
> +    begin.node_ = head_;
плохо

2023-06-18 14:14 UTC, Maxsmile123 commented on Nedosekin/KP8/src/List.cpp
> +Iterator<T> List<T>::erase(Iterator<T> where) noexcept
const&

2023-06-18 14:14 UTC, Maxsmile123 commented on Nedosekin/KP8/src/List.cpp
> +Iterator<T> List<T>::erase(Iterator<T> first, Iterator<T> last) noexcept
const&

2023-06-18 14:14 UTC, Maxsmile123 commented on Nedosekin/KP8/src/List.cpp
> +Iterator<T> List<T>::insert(Iterator<T> pos, const T &value)
const&

2023-06-18 14:14 UTC, Maxsmile123 commented on Nedosekin/KP8/src/List.cpp
> +        Iterator<T> kMinusOneIt = begin() + (k - 2);
k-1 = KPrew?)
k+1 = KNext?)

2023-06-18 14:14 UTC, Maxsmile123 commented on Nedosekin/KP8/tests/main.cpp
> +int64_t transform(std::string& set)
const&
И вообще, пользователь не должен делать это руками. Может, перенести куда-нибудь в методы объекта?

2023-06-20 12:22 UTC, Dots109 commented on Nedosekin/KP8/tests/main.cpp
> +int64_t transform(std::string& set)
но ведь тогда нарушится шаблонность листа, если я буду при вставке элемента производить эту трансформацию

2023-06-22 11:25 UTC, closed without merging