fomin Lab24 var 58
Maxsmile123/MAI_109B_22 pull request #147
Opened 2023-06-25 19:14 UTC by Haliava

2023-06-26 16:34 UTC, Maxsmile123 requested changes

2023-06-26 16:34 UTC, Maxsmile123 commented on Fomin/lab24/include/Node.h
> +    friend class ExpressionTree;
Это не надо. Взаимодействие с деревом нужно выполнить через гетеры

2023-06-26 16:34 UTC, Maxsmile123 commented on Fomin/lab24/src/ExpressionTree.cpp
> +    while ((pos = expressionCopy.find(delimiter)) != std::string::npos) {
Этот алгоритм неэффективный и в худшем случае может отработать за O(N^2)
Иначе говоря: позор

2023-06-26 16:34 UTC, Maxsmile123 commented on Fomin/lab24/src/ExpressionTree.cpp
> +    delete node;
Надо сделать её nullptr

2023-06-26 16:34 UTC, Maxsmile123 commented on Fomin/lab24/src/ExpressionTree.cpp
> +Node *ExpressionTree::createTree(const std::string &postfix) {
Почему эта функция возвращает что-то? У нас объект, который хранит рут - мы можем его заполнить, возвращать ничего не нужно, это не Си

2023-06-26 16:34 UTC, Maxsmile123 commented on Fomin/lab24/src/ExpressionTree.cpp
> +    std::stack<Node *> stack;
Вероятно, тут ты ловишь UB. Функция стэка pop() вызывает деструктор объекта, т.е. твоя Нода будет удалена

2023-06-26 16:34 UTC, Maxsmile123 commented on Fomin/lab24/src/ExpressionTree.cpp
> +#include <stack>
Нельзя

2023-06-26 16:34 UTC, Maxsmile123 commented on Fomin/lab24/src/ExpressionTree.cpp
> +    //std::cout << newExpression << std::endl;
Надо убрать, незачем это тут хранить

2023-06-26 16:36 UTC, Haliava commented on Fomin/lab24/src/ExpressionTree.cpp
> +#include <stack>
ой

2023-06-26 16:39 UTC, Haliava commented on Fomin/lab24/src/ExpressionTree.cpp
> +    while ((pos = expressionCopy.find(delimiter)) != std::string::npos) {
задание гроб я по-другому никак не придумал

2023-06-26 16:53 UTC, Haliava commented on Fomin/lab24/src/ExpressionTree.cpp
> +    //std::cout << newExpression << std::endl;
убрал

2023-06-27 11:07 UTC, Maxsmile123 commented on Fomin/lab24/src/ExpressionTree.cpp
> +    while ((pos = expressionCopy.find(delimiter)) != std::string::npos) {
Та не, тут не в задании дело, а в алгоритме сплита)

2023-06-27 11:08 UTC, Maxsmile123 commented
Жду коммитов с изменениями

2023-06-27 16:23 UTC, Maxsmile123 requested changes

2023-06-27 16:23 UTC, Maxsmile123 commented on Fomin/lab24/src/ExpressionTree.cpp
> +#include "../../../Koncebalov/lab24/Stack.hpp"
хахахххаах
Не, так не пойдёт

2023-06-27 16:23 UTC, Maxsmile123 commented on Fomin/lab24/src/ExpressionTree.cpp
> +#include "../../../Huan/kp7/Vector.hpp"
Это даже забавно. Так нельзя, нужно самому это реализовывать

2023-06-27 17:11 UTC, merged