Lab21
Maxsmile123/MAI_109B_22 pull request #15
Opened 2023-03-07 21:21 UTC by tng00

2023-03-09 02:50 UTC, Maxsmile123 requested changes

2023-03-09 02:50 UTC, Maxsmile123 commented on Huan/lab21/lab21.py
> +dir_path = sys.argv[1]
Лучше не писать питонячий скрипт вот так. Оберни всё в функцию main() и вызывай её в самом конце файла, прописав такую строку:
```
if __name__ == 'main':
    main()
```

2023-03-09 02:50 UTC, Maxsmile123 commented on Huan/lab21/lab21.py
> +suffixes = set()
Кажется, кусок кода ниже заслуживает отдельной функции

2023-03-09 02:50 UTC, Maxsmile123 commented on Huan/lab21/lab21.py
> +    pattern = r".+\..+$"
А зачем ты создаёшь эту переменную при каждом шаге цикла, если она единная на весь цикл? 
Лучше вынести её за цикл и объявить один раз

2023-03-10 14:06 UTC, tng00 commented
fixed issues

2023-03-10 19:38 UTC, Maxsmile123 requested changes
Чуть-чуть косметики и норм

2023-03-10 19:38 UTC, Maxsmile123 commented on Huan/lab21/unique_suffixes.py
> +            if re.match(pattern, file):  # Поиск имён файлов по заданному шаблону
Комментарий излишний

2023-03-10 19:38 UTC, Maxsmile123 commented on Huan/lab21/unique_suffixes.py
> +    if len(sys.argv) != 2:                # Проверка количества параметров
И тут

2023-03-10 19:38 UTC, Maxsmile123 commented on Huan/lab21/unique_suffixes.py
> +    if not os.path.isdir(sys.argv[1]):    # Проверка, является ли аргумент директорией
И тут

2023-03-10 19:56 UTC, tng00 commented
comments have been removed

2023-03-11 10:24 UTC, Maxsmile123 approved these changes

2023-03-11 10:25 UTC, merged