added lab26
Maxsmile123/MAI_109B_22 pull request #169
Opened 2023-08-17 23:19 UTC by zerotonyq

2023-08-18 15:22 UTC, Maxsmile123 requested changes
Very very bad... Смотреть всё не стал. Поправь то, что написал(Или обоснуй выбор) и на этом закончим

2023-08-18 15:22 UTC, Maxsmile123 commented on Gigolaev/lab25/Makefile
У тебя два ПР с одними и теми же файлами - это конфликт при мерже

2023-08-18 15:22 UTC, Maxsmile123 commented on Gigolaev/lab26/README.md
Какой у тебя вариант и задание?

2023-08-18 15:22 UTC, Maxsmile123 commented on Gigolaev/lab26/include/MyDeque.hpp
> +    int capacity;
Почему int, а не size_t?

2023-08-18 15:22 UTC, Maxsmile123 commented on Gigolaev/lab26/include/MyDeque.hpp
> +    void insert_order(T value, int rear_bound);
Не понял по названию, что делает этот метод

2023-08-18 15:52 UTC, zerotonyq commented on Gigolaev/lab26/README.md
поправил

2023-08-18 15:52 UTC, zerotonyq commented on Gigolaev/lab26/include/MyDeque.hpp
> +using namespace std;
поправил

2023-08-18 15:52 UTC, zerotonyq commented on Gigolaev/lab26/include/MyDeque.hpp
> +    int capacity;
поправил

2023-08-18 15:52 UTC, zerotonyq commented on Gigolaev/lab26/include/MyDeque.hpp
> +    int front;
поправил

2023-08-18 15:53 UTC, zerotonyq commented on Gigolaev/lab26/include/MyDeque.hpp
> +    bool is_empty();
поправил

2023-08-18 15:55 UTC, zerotonyq commented on Gigolaev/lab26/include/MyDeque.hpp
> +    void insert_order(T value, int rear_bound);
Метод делает то же самое, что insert, только вставляет элемент в уже отсортированный кусок дека и при этом сохраняет "отсортированность", т.е. вставляет поочереди. Согласен, над названием надо было бы подумать.

2023-08-18 15:55 UTC, zerotonyq commented on Gigolaev/lab26/include/MyDeque.hpp~
поправил

2023-08-18 15:56 UTC, zerotonyq commented on Gigolaev/lab26/src/MyDeque.cpp
> +    capacity = 8;
решил взять за основу 8. Понимаю, цифра взята с потолка, но я подумал, так будет лучше, чтобы делать resize при capacity = 1/2/4

2023-08-18 15:57 UTC, zerotonyq commented on Gigolaev/lab26/src/MyDeque.cpp
> +    // cout << " i " << i;
поправил

2023-08-18 15:58 UTC, zerotonyq commented on Gigolaev/lab26/src/MyDeque.cpp
> +void MyDeque<T>::print() {
подумал, что это несущественно. Можно перегрузить <<, но это вроде никак не отразится на производительности и читаемости кода.

2023-08-19 17:15 UTC, Maxsmile123 requested changes

2023-08-19 17:15 UTC, Maxsmile123 commented on Gigolaev/lab25/Makefile
Это убрать наверное нужно? У тебя есть отдельный ПР на 25-ую, мы не сможем смержить два одновременно

2023-08-20 13:22 UTC, merged