Lab21
Maxsmile123/MAI_109B_22 pull request #17
Opened 2023-03-08 13:29 UTC by MeDGranD

Лабораторная номер 21

2023-03-09 02:57 UTC, Maxsmile123 requested changes
В целом, очень неплохо. Но нужно поправить некоторые моменты

2023-03-09 02:57 UTC, Maxsmile123 commented on Lyubarsky/lab21/Suffix.py
> +    olddir = os.getcwd()
Лучше разделить название из нескольких слов символом ```_```
Так легче читается

2023-03-09 02:57 UTC, Maxsmile123 commented on Lyubarsky/lab21/Suffix.py
> +def file_analysis(_suffix: int, _directory: str, _file: str):
А какой смысл несёт ведущее нижнее подчеркивание тут?

2023-03-09 02:57 UTC, Maxsmile123 commented on Lyubarsky/lab21/Suffix.py
> +s, n, d, f = getParameters() #Letters stands for name of each parameter
Названия переменных не о чём не говорят - мне придётся лезть в функцию и понимать, что они означают. А я ленивый

2023-03-09 02:57 UTC, Maxsmile123 commented on Lyubarsky/lab21/Suffix.py
> +startFile.close()
Лучше этот кусок обернуть в функцию main и вызывать код так:
```
if __name__ == 'main':
    main()
```

2023-03-09 02:57 UTC, Maxsmile123 commented on Lyubarsky/lab21/Suffix.py
> +startFile = open(f, "a+")
А зачем ты открываешь файл, а потом закрываешь его, так ничего и не сделав?

2023-03-09 02:57 UTC, Maxsmile123 commented on Lyubarsky/lab21/Suffix.py
> +    sys.exit()
Лучше бросить исключение, кмк
На ошибки пользователь более отзывается, чем на штатное завершение программы

2023-03-09 03:29 UTC, MeDGranD commented on Lyubarsky/lab21/Suffix.py
> +def file_analysis(_suffix: int, _directory: str, _file: str):
Так я пометил эти переменные как внутренние. Т.к. они используются только в одной функции.

2023-03-09 03:31 UTC, MeDGranD commented on Lyubarsky/lab21/Suffix.py
> +startFile = open(f, "a+")
Если файл существует - ничего не происходит. Если он не существует - то его размер 0 и он нам подходит, надо только его создать, что я и делаю. Это удобно, так как не надо каждый раз создавать новый пустой файл для записи - программа все сделает.

2023-03-09 10:46 UTC, MeDGranD commented on Lyubarsky/lab21/Suffix.py
> +    olddir = os.getcwd()
Заменил olddir на old_directory.

2023-03-09 10:47 UTC, MeDGranD commented on Lyubarsky/lab21/Suffix.py
> +s, n, d, f = getParameters() #Letters stands for name of each parameter
Переименовал каждую переменную (suffix, file_size, search_directory, output_file).

2023-03-09 10:47 UTC, MeDGranD commented on Lyubarsky/lab21/Suffix.py
> +startFile.close()
Добавил функцию и добавил условие на запуск.

2023-03-09 10:48 UTC, MeDGranD commented on Lyubarsky/lab21/Suffix.py
> +    sys.exit()
Программа теперь бросает простое исключение с тем же сообщением.

2023-03-09 22:32 UTC, Maxsmile123 commented on Lyubarsky/lab21/Suffix.py
> +def file_analysis(_suffix: int, _directory: str, _file: str):
Кажется, что это излишнее, ибо почти все аргументы используются только внутри функции. Обычно в питоне так объявляют приватные поля класса

2023-03-09 22:32 UTC, Maxsmile123 commented on Lyubarsky/lab21/Suffix.py
> +def file_analysis(_suffix: int, _directory: str, _file: str):
Но в целом, ладно

2023-03-09 22:45 UTC, Maxsmile123 requested changes

2023-03-09 22:45 UTC, Maxsmile123 commented on Lyubarsky/lab21/Suffix.py
> +                if (file[-len(_suffix):] == _suffix  or _suffix == ' '):
Параметр в квадратных скобках выглядит как чёрная непонятно работающая магия)

2023-03-09 22:45 UTC, Maxsmile123 commented on Lyubarsky/lab21/Suffix.py
> +                    os.chdir(old_directory)
А зачем эта манипуляция со сменой директории? Разве нельзя использовать просто относительные/абсолютные пути файлов?

2023-03-09 22:45 UTC, Maxsmile123 commented on Lyubarsky/lab21/Suffix.py
> +                    outputFile = open(_file, 'a+')
Рекомендую юзать только with open() 
Меньше шанс, что забудешь закрыть файл

2023-03-09 22:45 UTC, Maxsmile123 commented on Lyubarsky/lab21/Suffix.py
> +    startFile = open(output_file, "a+")
Мои вопросы лучше не resolveить, чтобы я мог продолжить диалог.
Смотри, если в файл тебе ничего не нужно будет писать(нужных имён не найдётся), то у тебя создатся пустой файл. Это выглядит не очень круто, я бы убрал это в основную функцию

2023-03-10 16:08 UTC, MeDGranD commented on Lyubarsky/lab21/Suffix.py
> +                    os.chdir(old_directory)
Убрал чехорду с директориями, теперь путь к файлу храниться в отдельной переменной

2023-03-10 16:10 UTC, MeDGranD commented on Lyubarsky/lab21/Suffix.py
> +    startFile = open(output_file, "a+")
Написал отдельную функцию для проверки файла. (Чтобы не переполнять основную функцию + это не ее задача).
Также файл создается только когда находит нужные файлы.

2023-03-10 19:41 UTC, Maxsmile123 commented on Lyubarsky/lab21/Suffix.py
> +def file_analysis(_suffix: int, _directory: str, _file: str, _file_size: int):
Название функции абстрактно и непонятно. + мне кажется, что оно делает что-то другое, а не просто анализирует файлы

2023-03-10 19:59 UTC, MeDGranD commented on Lyubarsky/lab21/Suffix.py
> +    parser.add_argument('-s',
Добавил (так же и в bash).

2023-03-10 20:00 UTC, MeDGranD commented on Lyubarsky/lab21/Suffix.py
> +def file_analysis(_suffix: int, _directory: str, _file: str, _file_size: int):
Изменил на record_file_with_suffix. (Т.к. ее главная функция найти файл с суффиксом и его запись).

2023-03-11 10:27 UTC, Maxsmile123 approved these changes

2023-03-11 10:27 UTC, merged