added lab24 correctly from new branch
Maxsmile123/MAI_109B_22 pull request #172
Opened 2023-08-21 11:18 UTC by zerotonyq

2023-08-21 12:27 UTC, Maxsmile123 requested changes

2023-08-21 12:27 UTC, Maxsmile123 commented on Gigolaev/lab24/include/Node.hpp
> +    data.clear();
Это лишнее, оно автоматически вызовет деструктор полей

2023-08-21 12:27 UTC, Maxsmile123 commented on Gigolaev/lab24/include/Node.hpp
> +    if(left)
delete nullptr не приведёт ни к чему ужасному

2023-08-21 12:27 UTC, Maxsmile123 commented on Gigolaev/lab24/include/Node.hpp~
> +#pragma once
Лишний файл

2023-08-21 12:27 UTC, Maxsmile123 commented on Gigolaev/lab24/include/Vector.hpp
> +#pragma once
Заинклудь из КП7, дублировать не нужно

2023-08-21 12:27 UTC, Maxsmile123 commented on Gigolaev/lab24/include/Vector.hpp~
> +#pragma once
Лишний файл

2023-08-21 12:27 UTC, Maxsmile123 commented on Gigolaev/lab24/tests/main.cpp
> +﻿#include <iostream>
Почему эти функции описаны в main.cpp, а не принадлежат структуре дерева выражений?

2023-08-21 12:27 UTC, Maxsmile123 commented on Gigolaev/lab24/tests/main.cpp~
> +﻿#include <iostream>
Лишние файлы

2023-08-21 16:16 UTC, zerotonyq commented on Gigolaev/lab24/include/Node.hpp~
> +#pragma once
поправил

2023-08-21 16:16 UTC, zerotonyq commented on Gigolaev/lab24/include/Node.hpp
> +    data.clear();
поправил

2023-08-21 16:17 UTC, zerotonyq commented on Gigolaev/lab24/include/Node.hpp
> +    if(left)
поправил

2023-08-21 16:17 UTC, zerotonyq commented on Gigolaev/lab24/include/Vector.hpp~
> +#pragma once
поправил

2023-08-21 16:18 UTC, zerotonyq commented on Gigolaev/lab24/tests/main.cpp~
> +﻿#include <iostream>
поправил

2023-08-21 16:41 UTC, zerotonyq commented on Gigolaev/lab24/tests/main.cpp
> +﻿#include <iostream>
поправил

2023-08-22 13:15 UTC, Maxsmile123 commented on Gigolaev/lab24/include/Vector.hpp
> +#pragma once
У тебя вектор в 23-ей лабе есть

2023-08-24 00:49 UTC, Maxsmile123 approved these changes

2023-08-24 00:49 UTC, merged