21 лаба
Maxsmile123/MAI_109B_22 pull request #20
Opened 2023-03-09 08:48 UTC by Kasaneru

2023-03-09 11:06 UTC, Maxsmile123 requested changes
Very good, but need small improve

2023-03-09 11:06 UTC, Maxsmile123 commented on Adamov/lab21/count_lines.py
> +count_lines(args.dir)
Лучше не писать питонячий скрипт вот так. Оберни всё в функцию main() и вызывай её в самом конце файла, прописав такую строку:
```
if __name__ == 'main':
    main()
```

2023-03-09 11:06 UTC, Maxsmile123 commented on Adamov/lab21/count_lines.py
> +                global total_lines
Глобальные переменные не очень рекомендуются. Но, допустим, что ок

2023-03-09 12:00 UTC, Kasaneru commented
Фикс

2023-03-09 23:36 UTC, Maxsmile123 requested changes

2023-03-09 23:36 UTC, Maxsmile123 commented on Adamov/lab21/count_lines.py
> +    parser = ArgumentParser(description='Count lines in *.h and *.cpp files in directory recursively.')
Имелось ввиду, что ты объявишь функцию main()
В которой будут эти 5 строк
И функцию main() вызовешь из под этой проверки.
Так принято :)

2023-03-10 10:16 UTC, Kasaneru commented on Adamov/lab21/count_lines.py
> +    parser = ArgumentParser(description='Count lines in *.h and *.cpp files in directory recursively.')
Добавил.

2023-03-10 10:20 UTC, Maxsmile123 commented
Кайф, можешь писать отчёт

2023-03-10 10:20 UTC, merged