Burganova Elina Lab 21 advanced
Maxsmile123/MAI_109B_22 pull request #22
Opened 2023-03-09 13:12 UTC by Ellinois4

2023-03-09 23:39 UTC, Maxsmile123 commented on Burganova/lab21/DeleteMatchingFiles.py
> +def checkFileExsist(inputFileName):
В целом, кажется, это не заслуживает отдельной функции)
Но да ладно

2023-03-09 23:44 UTC, Maxsmile123 requested changes

2023-03-09 23:44 UTC, Maxsmile123 commented on Burganova/lab21/DeleteMatchingFiles.py
> +    if suffix == baseFileName[beginOfCut:endOfCut]:
У тебя оператор ```==``` возвращает тип bool. 
Наверное, намного проще заменить всё это на
``` return suffix == baseFileName[beginOfCut:endOfCut]```

2023-03-09 23:44 UTC, Maxsmile123 commented on Burganova/lab21/DeleteMatchingFiles.py
> +        return print("File not found!")
Лучше бросить исключение

2023-03-09 23:44 UTC, Maxsmile123 commented on Burganova/lab21/DeleteMatchingFiles.py
> +        return print("File's suffix doesn't match entered suffix")
Тут тоже исключение

2023-03-09 23:44 UTC, Maxsmile123 commented on Burganova/lab21/DeleteMatchingFiles.py
> +        if checkFileExsist(file) and file != inputFileName:
А зачем тут два вложенных if'а? 
Давай заменим на один с 4-ымя условиями - так проще. Строка получится очень длинной - попробуй воспользоваться онлайн форматором для питона или установи себе локально форматтер black

2023-03-09 23:44 UTC, Maxsmile123 commented on Burganova/lab21/DeleteMatchingFiles.py
> +                os.remove(file)
А что будет, если у нас нет прав доступа для удаления этого файла?

2023-03-11 12:08 UTC, Ellinois4 commented on Burganova/lab21/DeleteMatchingFiles.py
> +                os.remove(file)
Добавила блок try except. Теперь исключение обрабатывается и программа продолжает работать при его возникновении. Пользователю выводится ошибка Permission denied и имя файла, к которому запрещен доступ

2023-03-11 13:27 UTC, Maxsmile123 approved these changes
Мне ок

2023-03-11 13:27 UTC, merged