Lab21
Maxsmile123/MAI_109B_22 pull request #26
Opened 2023-03-10 02:17 UTC by hedgefo9

2023-03-10 19:13 UTC, Maxsmile123 requested changes
Разбей главную функцию на несколько. В остальном очень гуд

2023-03-10 19:13 UTC, Maxsmile123 commented on Fedorov/lab21/del-files-suff-days.py
> +    if len(sys.argv) != 4:
Давай сделаем это через argparse. Там есть параметр ```required```, который делает параметр обязательным

2023-03-10 19:13 UTC, Maxsmile123 commented on Fedorov/lab21/del-files-suff-days.py
> +def main():
Давай разобъём скрипт на несколько функций. В main() только сбор аргументов и вызов функции, которая что-то делает

2023-03-10 19:13 UTC, Maxsmile123 commented on Fedorov/lab21/del-files-suff-days.py
> +        print("Syntax: del-files-suff-days path suffix days")
Если что, можно сделать один принт. Если хочешь нову строку, используй символ ```\n```

2023-03-11 10:13 UTC, hedgefo9 commented on Fedorov/lab21/del-files-suff-days.py
> +    if len(sys.argv) != 4:
исправил

2023-03-11 10:13 UTC, hedgefo9 commented on Fedorov/lab21/del-files-suff-days.py
> +        print("Syntax: del-files-suff-days path suffix days")
исправил

2023-03-11 10:13 UTC, hedgefo9 commented on Fedorov/lab21/del-files-suff-days.py
> +def main():
исправил

2023-03-11 10:31 UTC, Maxsmile123 approved these changes

2023-03-11 10:31 UTC, merged