Efimenko kirill
Maxsmile123/MAI_109B_22 pull request #3
Opened 2023-02-21 21:38 UTC by vivichv9

лабораторная работа 21, поток advanced

2023-02-22 11:49 UTC, Maxsmile123 reviewed
Надо исправить

2023-02-22 11:49 UTC, Maxsmile123 commented on Efimenko/lab21/run.sh
> +read suffix
Ааа нет, нужно принимать параметры из командной строки. Т.е. запуск должен выглядеть как: ./run.sh suffix filename

2023-02-22 11:49 UTC, Maxsmile123 commented on Efimenko/lab21/run.py
> +suffix = input("Enter suffix: ")
Нужно принимать параметры из командной строки. Тут поможет библиотека argparse. Запуск должен выглядеть примерно так:
python3 run.py -s suffix -f filename

2023-02-22 11:49 UTC, Maxsmile123 commented on Efimenko/lab21/run.py
> +
В целом, очень плохо писать питонячий скрипт вот так. Разбей всё на человеческие функции и запускай код в функции main()

2023-02-22 11:49 UTC, Maxsmile123 commented on Efimenko/lab21/run.py
> +    fileCopy = fileCopy[0]
А если у меня файл формата с тремя точками, четырьмя и больше?
Например: msg.txt.gpg

Тогда твой скрипт будет работать неверно

2023-02-22 11:49 UTC, Maxsmile123 commented on Efimenko/lab21/run.py
> +    fileCopy = fileCopy[len(fileCopy) - len(suffix):len(fileCopy)]
Это нужно упростить, слишком сложно

2023-02-22 11:49 UTC, Maxsmile123 commented on Efimenko/lab21/run.py
> +outFile = input(
А почему только абсолютный путь? Почему нельзя относительный?

2023-02-22 11:49 UTC, Maxsmile123 commented on Efimenko/lab21/run.py
> +    os.remove(outFile)
Зачем?

2023-02-22 11:49 UTC, Maxsmile123 commented on Efimenko/lab21/run.py
> +            print(f'{file} is executable!')
Лучше это убрать, чтобы не было лишнего вывода. Ты скорее всего имел ввиду логи - для этого лучше использовать библиотеку logger и писать логи в отдельный файл, не в stdout

2023-02-23 12:10 UTC, vivichv9 commented on Efimenko/lab21/run.py
> +    os.remove(outFile)
Просто там, в проге через команду tee -a идет добавление в конец файла. Если файл уже будет существовать, то прога просто запишет все в него, а он может быть не пустым. Поэтому, я сначала его удаляю.
Но думаю, что нужно останавливать прогу, чтоб данные не потерялись

2023-02-23 14:32 UTC, Maxsmile123 commented on Efimenko/lab21/run.py
> +            if os.access(file, os.X_OK) == False:
Давай всё таки вспомним, что в python есть логические операторы and и or. Очень большая вложенность if'ов - это можно поправить. При этом, проверяй свой код при помощи форматтера flake8(почитай про него - он выводит ошибки от кодстайла PEP8)

2023-02-23 14:32 UTC, Maxsmile123 commented on Efimenko/lab21/run.py
> +                        fileOut.write(f'echo {file} {fileSize}\n')
А зачем тут echo?

2023-02-23 14:32 UTC, Maxsmile123 commented on Efimenko/lab21/run.py
> +    nowTime = now.time()
Зачем? Ты же это даже не используешь

2023-02-23 14:37 UTC, vivichv9 commented on Efimenko/lab21/run.py
> +    nowTime = now.time()
Это чтобы в качестве дефолтного имени выходного файла было текущее время. Просто чтобы были всегда разные имена по дефолту

2023-02-23 14:38 UTC, vivichv9 commented on Efimenko/lab21/run.py
> +                        fileOut.write(f'echo {file} {fileSize}\n')
Это осталась от прошлого кода небольшая помарка)) поправлю

2023-02-23 22:49 UTC, vivichv9 commented on Efimenko/lab21/run.py
> +            if os.access(file, os.X_OK) == False:
Поправил, вместо 4 ифов сделал 2
если 1 иф сделать, то будет прям сложно прочитать

2023-02-24 00:40 UTC, Maxsmile123 requested changes
Не закрыл файлик

2023-02-24 00:40 UTC, Maxsmile123 commented on Efimenko/lab21/run.py
> +    fileOut = open(outFile, 'w')
Тут ошибка - файл открыл, но не закрыл. Погугли рекомендуемую конструкцию для файлов with open(...) as file:

2023-02-24 16:28 UTC, merged