23_laba_stepanov
Maxsmile123/MAI_109B_22 pull request #51
Opened 2023-04-08 09:25 UTC by Alexstepano

21 лабораторная работа, 2 вариант, надеюсь, все будет ок.

2023-04-12 16:40 UTC, Maxsmile123 requested changes
Файлы следует разделить на интерфейс и на исходиники. Писать реализацию в hpp - плохая идея 
P.s. я так делаю на занятиях, потому что это быстрее

2023-04-15 00:04 UTC, Maxsmile123 requested changes

2023-04-15 00:04 UTC, Maxsmile123 commented on Stepanov/lab23/src/Tree.cpp
> +            root = root->Node<T>::Delete_Node(root, var_for_search_for_deleting);
Единственное отличие от строчки ниже это то, что теперь тут присваивание. Зачем?

2023-04-15 00:04 UTC, Maxsmile123 commented on Stepanov/lab23/tests/main.cpp
> +    //std::cin >> y;
Комменты стоит убрать, конечно

2023-04-15 08:51 UTC, Alexstepano commented on Stepanov/lab23/include/Node.hpp
> +    Node(T new_data);
Изменил, теперь копия

2023-04-15 08:52 UTC, Alexstepano commented on Stepanov/lab23/include/Node.hpp
> +    int64_t B_tree_bypass(const Node *node) const;
Теперь написания функций -  с маленькой

2023-04-15 08:52 UTC, Alexstepano commented on Stepanov/lab23/include/Node.hpp
> +    Node *Delete_Node(Node *node, T variable_of_interest);
Перестройка дерева требует возвращение ноды после удаления

2023-04-15 08:52 UTC, Alexstepano commented on Stepanov/lab23/include/Node.hpp
> +    Node *add_leaf(const T insert_data, Node *working_node);
Починил

2023-04-15 09:09 UTC, Maxsmile123 requested changes

2023-04-15 09:09 UTC, Maxsmile123 commented on Stepanov/lab23/src/Node.cpp
> +void Node<T>::print_nodes(Node<T> *node, int64_t counter) const
Высота, наверное?

2023-04-15 09:09 UTC, Maxsmile123 commented on Stepanov/lab23/src/Node.cpp
> +        Node<T>::delete_branch(deleting_node->left);
:( Приставка

2023-04-15 09:10 UTC, Alexstepano commented on Stepanov/lab23/src/Node.cpp
> +Node<T> *Node<T>::Delete_Node(Node<T> *node, T variable_of_interest)
очно объяснил

2023-04-15 09:12 UTC, Alexstepano commented on Stepanov/lab23/src/Node.cpp
> +Node<T> *Node<T>::add_leaf(const T insert_data, Node<T> *working_node)
cur node

2023-04-15 10:14 UTC, Alexstepano commented on Stepanov/lab23/src/Tree.cpp
> +Tree<T>::Tree() : root(nullptr)
Выдает ошибку, ибо заполняет не nullptr, а указателем на мусор

2023-04-15 10:14 UTC, Alexstepano commented on Stepanov/lab23/src/Tree.cpp
> +void Tree<T>::delete_node(T var_for_search_for_deleting)
изменил

2023-04-15 10:15 UTC, Alexstepano commented on Stepanov/lab23/tests/main.cpp
> +    //std::cin >> y;
убрал

2023-04-15 10:15 UTC, Alexstepano commented on Stepanov/lab23/include/Node.hpp
> +    Node(const T& new_data);
Добавил

2023-04-15 10:15 UTC, Alexstepano commented on Stepanov/lab23/src/Node.cpp
> +void Node<T>::print_nodes(Node<T> *node, int64_t counter) const
Изменил

2023-04-15 10:16 UTC, Alexstepano commented on Stepanov/lab23/src/Node.cpp
> +        Node<T>::delete_branch(deleting_node->left);
Убрал в этом месте и в удалении узла с перестройкой дерева

2023-04-15 10:22 UTC, Alexstepano commented on Stepanov/lab23/src/Node.cpp
> +Node<T> *Node<T>::add_leaf(const T insert_data, Node<T> *working_node)
исправил

2023-04-15 10:22 UTC, Alexstepano commented on Stepanov/lab23/include/Node.hpp
> +    void print_nodes(Node *node, int64_t counter) const;
:3

2023-04-15 17:35 UTC, Alexstepano commented on Stepanov/lab23/include/Node.hpp
> +    void print_nodes(Node *node, int64_t counter) const;
Перегрузил, теперь можно и через оператор дерево выводить

2023-04-16 09:41 UTC, Maxsmile123 approved these changes
В целом, ок. Но я ещё локально протестирую у себя на разных входных данных

2023-04-20 16:07 UTC, merged