Fedorov lab23
Maxsmile123/MAI_109B_22 pull request #54
Opened 2023-04-15 17:58 UTC by hedgefo9

2023-04-20 19:18 UTC, Maxsmile123 requested changes
Утечек нет, есть пару косметических замечаний

2023-04-20 19:18 UTC, Maxsmile123 commented on Fedorov/lab23/include/Node.hpp
> +    Node()=default;
Пробелов бы

2023-04-20 19:18 UTC, Maxsmile123 commented on Fedorov/lab23/include/Node.hpp
> +    ~Node()=default;
И тут

2023-04-20 19:18 UTC, Maxsmile123 commented on Fedorov/lab23/include/Node.hpp
> +    Node<T> *min_value_node(Node<T> *node);
Вероятно, метод const?

2023-04-20 19:18 UTC, Maxsmile123 commented on Fedorov/lab23/include/Tree.hpp
> +    Tree()=default;
пробелы

2023-04-20 19:18 UTC, Maxsmile123 commented on Fedorov/lab23/include/Tree.hpp
> +    explicit Tree(Node<T> *node);
Почему не const в аргументах?

2023-04-20 19:18 UTC, Maxsmile123 commented on Fedorov/lab23/src/Node.cpp
> +Node<T> *Node<T>::min_value_node(Node<T> *node) {
метод конст, как и нода

2023-04-21 08:17 UTC, hedgefo9 commented on Fedorov/lab23/include/Node.hpp
> +    Node()=default;
добавил

2023-04-21 08:17 UTC, hedgefo9 commented on Fedorov/lab23/include/Node.hpp
> +    ~Node()=default;
добавил

2023-04-21 08:17 UTC, hedgefo9 commented on Fedorov/lab23/include/Node.hpp
> +    Node<T> *min_value_node(Node<T> *node);
поправил

2023-04-21 08:17 UTC, hedgefo9 commented on Fedorov/lab23/include/Tree.hpp
> +    Tree()=default;
добавил

2023-04-21 08:18 UTC, hedgefo9 commented on Fedorov/lab23/include/Tree.hpp
> +    explicit Tree(Node<T> *node);
поправил

2023-04-21 08:18 UTC, hedgefo9 commented on Fedorov/lab23/src/Node.cpp
> +Node<T> *Node<T>::min_value_node(Node<T> *node) {
поправил

2023-04-21 17:57 UTC, Maxsmile123 approved these changes
Кайф, можно писать отчёт

2023-04-21 17:57 UTC, merged