Lab 23 variant 24 Huan
Maxsmile123/MAI_109B_22 pull request #56
Opened 2023-04-20 08:54 UTC by tng00

Find the depth of a tree (general form).

2023-04-21 22:22 UTC, Maxsmile123 requested changes
Тесты гуд, но проверь на утечки, есть опасения

2023-04-21 22:22 UTC, Maxsmile123 commented on Huan/lab23/include/Node.hpp
> +  Node<T> **children;
А почему они публичные? Публичный указатель - звучит очень страшно

2023-04-21 22:22 UTC, Maxsmile123 commented on Huan/lab23/include/Node.hpp
> +  Node(T val);
explicit?
Почему копия, а не конст ссылка?

2023-04-21 22:22 UTC, Maxsmile123 commented on Huan/lab23/include/Node.hpp
> +  int  get_num_children() const;
Лучше size_t, ибо кол-во детей точно не может быть отрицательным

2023-04-21 22:22 UTC, Maxsmile123 commented on Huan/lab23/include/Tree.hpp
> +  Node<T> *root;
Почему паблик? Давай приватным сделаем и напишем гетер

2023-04-21 22:22 UTC, Maxsmile123 commented on Huan/lab23/include/Tree.hpp
> +  int depth() const;
size_t

2023-04-21 22:22 UTC, Maxsmile123 commented on Huan/lab23/src/Node.cpp
> +  for (int i = 0; i < num_children; i++) {
size_t

2023-04-21 22:22 UTC, Maxsmile123 commented on Huan/lab23/src/Node.cpp
> +  children = (Node<T> **) realloc(children, (num_children + 1) * sizeof(Node<T> *));
А давай откажемся от СИ стайла в пользу плюсов? Лучше не использовать malloc и realloc, отдавая предпочтение new и delete

2023-04-21 22:22 UTC, Maxsmile123 commented on Huan/lab23/src/Node.cpp
> +  children = (Node<T> **) realloc(children, num_children * sizeof(Node<T> *));
Тоже самое

2023-04-21 22:22 UTC, Maxsmile123 commented on Huan/lab23/src/Node.cpp
> +  num_children--;
А почему ты используешь постфиксный инкремент, вместо префиксного?

2023-04-21 22:22 UTC, Maxsmile123 commented on Huan/lab23/src/Tree.cpp
> +  root = nullptr;
Для этого стоило писать конструктор по умолчанию?

2023-04-21 22:22 UTC, Maxsmile123 commented on Huan/lab23/src/Tree.cpp
> +  delete root;
Проверял на утечки памяти? make test должен отработать без ошибок

2023-06-03 08:57 UTC, tng00 commented on Huan/lab23/include/Node.hpp
> +  int  get_num_children() const;
пофиксил

2023-06-03 08:57 UTC, tng00 commented on Huan/lab23/include/Tree.hpp
> +  Node<T> *root;
пофиксил

2023-06-03 08:57 UTC, tng00 commented on Huan/lab23/include/Tree.hpp
> +  int depth() const;
пофиксил

2023-06-03 08:57 UTC, tng00 commented on Huan/lab23/src/Node.cpp
> +  for (int i = 0; i < num_children; i++) {
пофиксил

2023-06-03 08:58 UTC, tng00 commented on Huan/lab23/include/Node.hpp
> +  Node(T val);
забыл, сделал конст ссылку

2023-06-03 09:07 UTC, tng00 commented on Huan/lab23/src/Node.cpp
> +  children = (Node<T> **) realloc(children, (num_children + 1) * sizeof(Node<T> *));
пофиксил

2023-06-03 09:15 UTC, tng00 commented on Huan/lab23/src/Node.cpp
> +  children = (Node<T> **) realloc(children, num_children * sizeof(Node<T> *));
пофиксил

2023-06-03 09:18 UTC, tng00 commented on Huan/lab23/src/Node.cpp
> +  num_children--;
по настроению юзаю если это ни на что не влияет. сделал везде префиксный

2023-06-03 09:20 UTC, tng00 commented on Huan/lab23/src/Tree.cpp
> +  root = nullptr;
неа. сделал все в одну строчку в Tree.hpp

2023-06-03 09:37 UTC, tng00 commented on Huan/lab23/src/Tree.cpp
> +  delete root;
да, все норм

tng00@DESKTOP-AE5RPFC:~/lab23$ make
mkdir bin
Building...
g++ -std=c++17 -Wall -fsanitize=address -I include -L lib tests/main.cpp -o bin/main -lstdc++ -lm
tng00@DESKTOP-AE5RPFC:~/lab23$

2023-06-03 09:52 UTC, tng00 commented on Huan/lab23/include/Node.hpp
> +  Node<T> **children;
хотел так получать потомков в мейне, сделал геттер

2023-06-03 09:54 UTC, tng00 commented
по утечкам все норм. в деструкторе tree делаю delete root, а в деструкторе node рекурсивно удаляются все потомки. makefile не ругается

2023-06-03 15:16 UTC, Maxsmile123 requested changes
Поправь кодстайл

2023-06-03 15:16 UTC, Maxsmile123 commented on Huan/lab23/include/Node.hpp
> +#include <algorithm>
Это нельзя использовать

2023-06-03 15:16 UTC, Maxsmile123 commented on Huan/lab23/include/Tree.hpp
> +
Нужно ещё добавить функцию поиска элемента

2023-06-03 18:04 UTC, tng00 commented on Huan/lab23/include/Node.hpp
> +#include <algorithm>
оно не используется, случайно сюда попало, убрал

2023-06-03 18:04 UTC, tng00 commented on Huan/lab23/include/Tree.hpp
> +
сделано

2023-06-03 18:10 UTC, tng00 commented
сделал форматирование в clion по гугловскому код-стайлу (выбрал в настройках)

2023-06-05 09:49 UTC, Maxsmile123 approved these changes

2023-06-05 09:49 UTC, merged