Lab23 done
Maxsmile123/MAI_109B_22 pull request #59
Opened 2023-04-21 21:00 UTC by MeDGranD

Вариант: 12;
Задание: Проверить, является ли двоичное дерево линейным списком вершин.

2023-04-21 22:34 UTC, Maxsmile123 requested changes

2023-04-21 22:34 UTC, Maxsmile123 commented on Lyubarsky/lab23/include/Tree.hpp
> +    TreeNode<T>* root = nullptr;
Почему паблик?

2023-04-21 22:34 UTC, Maxsmile123 commented on Lyubarsky/lab23/include/TreeNode.hpp
> +    TreeNode(T);
const& ?

2023-04-21 22:34 UTC, Maxsmile123 commented on Lyubarsky/lab23/include/TreeNode.hpp
> +    TreeNode(T, TreeNode*, TreeNode*);
const& ?

2023-04-21 22:34 UTC, Maxsmile123 commented on Lyubarsky/lab23/include/TreeNode.hpp
> +    T data;
Почему паблик?

2023-04-21 22:34 UTC, Maxsmile123 commented on Lyubarsky/lab23/src/Tree.cpp
> +    if (node->data == newData) {
А почему ты не можешь хранить одинаковые данные? Бинарное дерево поиска позволяет хранить одинаковые по значению элементы

2023-04-21 22:34 UTC, Maxsmile123 commented on Lyubarsky/lab23/src/Tree.cpp
> +    if ((node->nextRightNode != nullptr) && (node != root)) { linear = false; return;}
Давай соблюдать кодстайл. Так писать не красиво (речь про скобки в одну строчку)

2023-04-21 22:34 UTC, Maxsmile123 commented on Lyubarsky/lab23/src/Tree.cpp
> +    if (!linear) {
А можно как-то избежать этой копипасты?

2023-04-21 22:34 UTC, Maxsmile123 commented on Lyubarsky/lab23/src/Tree.cpp
> +    deleteTree(root);
Вообще, это можно реализовать итеративно прямо в деструкторе, но это ладно

2023-04-21 22:34 UTC, Maxsmile123 commented on Lyubarsky/lab23/src/Tree.cpp
> +    deleteTree(root);
Просто рекурсия плоха тем, что у тебя может переполнится стек вызовов(когда дерево огромное). И тогда ты словишь огромную утечку памяти. Это так, для понимания, переделывать необязательно

2023-04-22 17:46 UTC, MeDGranD commented on Lyubarsky/lab23/include/Tree.hpp
> +    TreeNode<T>* root = nullptr;
Исправил путем перевода всех полей в private.

2023-04-22 17:47 UTC, MeDGranD commented on Lyubarsky/lab23/include/TreeNode.hpp
> +    TreeNode(T);
Исправил.

2023-04-22 17:47 UTC, MeDGranD commented on Lyubarsky/lab23/include/TreeNode.hpp
> +    TreeNode(T, TreeNode*, TreeNode*);
Исправил.

2023-04-22 17:48 UTC, MeDGranD commented on Lyubarsky/lab23/include/TreeNode.hpp
> +    T data;
Исправил, переведя все поля в private. +  назначит класс Tree friend`ом класса TreeNode.

2023-04-22 17:48 UTC, MeDGranD commented on Lyubarsky/lab23/src/Tree.cpp
> +    if (node->data == newData) {
Теперь одинаковые данные храняться (одинаковый нод уводит в правую ветвь)

2023-04-22 17:49 UTC, MeDGranD commented on Lyubarsky/lab23/src/Tree.cpp
> +    if ((node->nextRightNode != nullptr) && (node != root)) { linear = false; return;}
Исправил это недоразумение.

2023-04-22 17:50 UTC, MeDGranD commented on Lyubarsky/lab23/src/Tree.cpp
> +    if (!linear) {
Теперь для вывода проверяется только перед выходом со стека рекурсии.

2023-04-25 17:41 UTC, Maxsmile123 requested changes

2023-04-25 17:41 UTC, Maxsmile123 commented on Lyubarsky/lab23/include/Tree.hpp
> +    TreeNode<T>* getRoot();
Почему не const?

2023-04-27 11:40 UTC, MeDGranD commented on Lyubarsky/lab23/include/Tree.hpp
> +    TreeNode<T>* getRoot();
Теперь const

2023-04-28 12:38 UTC, Maxsmile123 requested changes

2023-04-28 13:18 UTC, MeDGranD commented on Lyubarsky/lab23/README.md
Он же стоит.

2023-05-02 12:27 UTC, Maxsmile123 approved these changes

2023-05-02 12:27 UTC, merged