Kp 7 stepanov
Maxsmile123/MAI_109B_22 pull request #60
Opened 2023-04-25 07:23 UTC by Alexstepano

Курсовая работа №7,  вариант 2,2 , надеюсь, все будет ок.

2023-04-25 18:13 UTC, Maxsmile123 requested changes
Кошмар..

2023-04-25 18:13 UTC, Maxsmile123 commented on Stepanov/KP7/src/Vector.cpp
> +        resize(0, 0);
Какая-то дичь - если вектор хранит объект, а ты ему 0 суёшь как дефолтное значение?...

2023-04-25 18:13 UTC, Maxsmile123 commented on Stepanov/KP7/src/Vector.cpp
> +        T *new_arr = reinterpret_cast<T *>(new int8_t[sz * sizeof(T)]);
Эм...зачем ты в этом методе делаешь копию вектора?....
Его цель - свести cap к sz, удалив неиспользуемую память

2023-04-25 18:13 UTC, Maxsmile123 commented on Stepanov/KP7/src/Vector.cpp
> +T &Vector<T>::operator[](size_t pos)
Чем это отличается от метода at? Почитай на cppreference разницу между at и []

2023-04-25 18:13 UTC, Maxsmile123 commented on Stepanov/KP7/src/Vector.cpp
> +            if (this->at(i) != b.at(i)) {
Зачем тут at?

2023-04-25 18:13 UTC, Maxsmile123 commented on Stepanov/KP7/include/Matrix.hpp
> +    size_t msz;
Это хранит не нужно - у тебя задание -> сделайте матрицу из одного вектора. А не одного вектора и двух переменных

2023-04-25 18:13 UTC, Maxsmile123 commented on Stepanov/KP7/src/Matrix.cpp
> +    x.matrix_in_line.pop_back();
Это зачем?

2023-04-25 18:13 UTC, Maxsmile123 commented on Stepanov/KP7/src/Matrix.cpp
> +std::istream &operator>>(std::istream &o, Matrix &x)
Почему ты поток назвал одной буквой? Давай найдём лучшие названия для переменных, чем просто буква

2023-04-25 18:13 UTC, Maxsmile123 commented on Stepanov/KP7/src/Matrix.cpp
> +    int64_t l, m_i, n_i;
Что за l?

2023-04-25 18:13 UTC, Maxsmile123 commented on Stepanov/KP7/src/Matrix.cpp
> +        if (x.matrix_in_line.back() != 0) {
Зачем?

2023-04-25 18:13 UTC, Maxsmile123 commented on Stepanov/KP7/src/Matrix.cpp
> +    x.matrix_in_line.push_back(0);
Зачем?

2023-04-25 18:13 UTC, Maxsmile123 commented on Stepanov/KP7/src/Matrix.cpp
> +std::ostream &operator<<(std::ostream &o, Matrix &x)
Имена получше бы

2023-04-25 18:13 UTC, Maxsmile123 commented on Stepanov/KP7/src/Matrix.cpp
> +    bool is_it_poz = true, needed_column = false;
Названия ужасные

2023-04-25 18:13 UTC, Maxsmile123 commented on Stepanov/KP7/src/Matrix.cpp
> +        else if (is_it_poz) {
Можно обойтись без булевских флагов? Это выглядит ужасно

2023-04-25 18:13 UTC, Maxsmile123 commented on Stepanov/KP7/src/Matrix.cpp
> +            if (mod_max_elem < (matrix_in_line[y] < 0 ? (-1) * matrix_in_line[y] : matrix_in_line[y])) {
Этот иф - самое страшное, что я видел за последнее время. Давай упростим

2023-04-25 18:13 UTC, Maxsmile123 commented on Stepanov/KP7/src/Matrix.cpp
> +    temp_vector.push_back(0);
Зачем?

2023-04-25 18:13 UTC, Maxsmile123 commented on Stepanov/KP7/src/Matrix.cpp
> +void Matrix::find_max_and_divide()
В целом, этот метод нужно как можно сильнее упростить и разбить на функции - он очень громоздкий

2023-04-26 07:18 UTC, Alexstepano commented on Stepanov/KP7/src/Vector.cpp
> +            throw std::range_error("Too big accsesed memory");
Ок, убрал проверку на переполнение

2023-04-26 07:18 UTC, Alexstepano commented on Stepanov/KP7/src/Vector.cpp
> +    if (cap != 0) {
Убрал

2023-04-26 07:19 UTC, Alexstepano commented on Stepanov/KP7/src/Vector.cpp
> +void Vector<T>::resize(size_t n, const T &value)
Оно прописано в Vector.hpp

2023-04-26 07:19 UTC, Alexstepano commented on Stepanov/KP7/src/Vector.cpp
> +    if (cap != 0) {
Убрал

2023-04-26 07:20 UTC, Alexstepano commented on Stepanov/KP7/src/Vector.cpp
> +        throw std::exception();
Убрал вместе с if

2023-04-26 07:20 UTC, Alexstepano commented on Stepanov/KP7/src/Vector.cpp
> +                throw std::range_error("Too big accsesed memory");
Убрал лишние проверки

2023-04-26 07:21 UTC, Alexstepano commented on Stepanov/KP7/src/Vector.cpp
> +    if (cap != 0) {
Убрал

2023-04-26 07:21 UTC, Alexstepano commented on Stepanov/KP7/src/Vector.cpp
> +        if (n < sz) {
Убрал не очень нужные if + починил баг

2023-04-26 07:21 UTC, Alexstepano commented on Stepanov/KP7/src/Vector.cpp
> +        throw std::exception();
Убрал

2023-04-26 07:22 UTC, Alexstepano commented on Stepanov/KP7/src/Vector.cpp
> +            if (cap * 2 < cap) {
Убрал проверку на преполнение

2023-04-26 07:23 UTC, Alexstepano commented on Stepanov/KP7/src/Vector.cpp
> +            throw std::range_error("Can not pop,if vector is empty");
Ок, поставил return

2023-04-26 07:23 UTC, Alexstepano commented on Stepanov/KP7/src/Vector.cpp
> +    delete[] reinterpret_cast<char *>(arr);
Согласен, теперь прохожусь и удаляю существующие объекты

2023-04-26 07:24 UTC, Alexstepano commented on Stepanov/KP7/src/Vector.cpp
> +    sz = 0;
:( ради безопасности

2023-04-26 07:25 UTC, Alexstepano commented on Stepanov/KP7/src/Vector.cpp
> +        resize(0, 0);
Переделал clear в целом

2023-04-26 07:25 UTC, Alexstepano commented on Stepanov/KP7/src/Vector.cpp
> +        T *new_arr = reinterpret_cast<T *>(new int8_t[sz * sizeof(T)]);
Переделал shrink_to_fit, убрав ненужную копию вектора

2023-04-26 07:26 UTC, Alexstepano commented on Stepanov/KP7/src/Vector.cpp
> +T &Vector<T>::operator[](size_t pos)
Убрал проверку на выход за пределы vectorа

2023-04-26 07:27 UTC, Alexstepano commented on Stepanov/KP7/src/Matrix.cpp
> +std::istream &operator>>(std::istream &o, Matrix &x)
Переименовал переменные для потоков на более осмысленные

2023-04-26 07:28 UTC, Alexstepano commented on Stepanov/KP7/src/Matrix.cpp
> +std::ostream &operator<<(std::ostream &o, Matrix &x)
Изменил названия переменных для потоков на более осмысленные

2023-04-26 20:13 UTC, Alexstepano commented on Stepanov/KP7/src/Matrix.cpp
> +    bool is_it_poz = true, needed_column = false;
Постарался изменить на более ясные

2023-04-26 20:16 UTC, Alexstepano commented on Stepanov/KP7/src/Matrix.cpp
> +        else if (is_it_poz) {
К сожалению, скорее всего нет, чем да. Этот флаг необходим нам для различения значений массива, отвечающих за номер столбца, где встречен ненулевой элемент, от самого значения в ячейке матрицы.(что никак не сигнализируется в  самих значениях массива - приходится подсчитывать самостоятельно)

2023-04-26 20:22 UTC, Alexstepano commented on Stepanov/KP7/src/Matrix.cpp
> +    x.matrix_in_line.pop_back();
Изначально, вектор матрицы представляет собой вектор с последовательностью из 2 0(терминирующая последовательность)=> для записи в него требуется убрать последний 0, а после окончания ввода матрицы снова его вернуть, сохранив тем самым вид вектора, соответсвуя условию задачи.

2023-04-26 20:25 UTC, Alexstepano commented on Stepanov/KP7/src/Matrix.cpp
> +        if (x.matrix_in_line.back() != 0) {
После введенной строки отвечает за постановку 0 в конец вектора, если введенная строка содержала хотя бы 1 ненулевое значение, иначе ввод нуля не требуется.Тем самым соблюдается разделение нулями концов и начал строк

2023-04-26 20:29 UTC, Alexstepano commented on Stepanov/KP7/src/Matrix.cpp
> +    temp_vector.push_back(0);
При делении мы сильно изменяем вид нашей матрицы(т.к. делим на максимальный элемент, то все меньшие его по модулю обратятся в 0 - потребуется убирать как и столпцы ранее заполненные, так и некоторые строки матрицы)=> за O(N)(где N -size вектора) мы преобразуем матрицу в соответсвии с условием и заменяем вектор в поле класса на новый

2023-04-26 20:31 UTC, Alexstepano commented on Stepanov/KP7/src/Matrix.cpp
> +    x.matrix_in_line.push_back(0);
Возвращаем убранный ноль в конец вектора

2023-04-26 20:31 UTC, Alexstepano commented on Stepanov/KP7/src/Matrix.cpp
> +    int64_t l, m_i, n_i;
Изменил, теперь названии более ясное

2023-04-26 20:32 UTC, Alexstepano commented on Stepanov/KP7/src/Matrix.cpp
> +void Matrix::find_max_and_divide()
Разбил на 2 части, чтобы был метод более читаемым

2023-04-28 12:42 UTC, Maxsmile123 requested changes
А где редми файл, в котором прописан вариант и задание?

2023-04-28 12:42 UTC, Maxsmile123 commented on Stepanov/KP7/src/Matrix.cpp
> +     int64_t  elem_from_div = 0;
Тут поехало немного - лишний пробел

2023-04-28 12:42 UTC, Maxsmile123 commented on Stepanov/KP7/src/Matrix.cpp
> +    int64_t cur_max_collumn = 0, prev_max_collumn = 0, cur_collumn = 0, max_elem = 0, mod_max_elem = 0;
Вроде, column пишется с одной буквой l

2023-04-28 19:42 UTC, Alexstepano commented on Stepanov/KP7/src/Matrix.cpp
> +    int64_t cur_max_collumn = 0, prev_max_collumn = 0, cur_collumn = 0, max_elem = 0, mod_max_elem = 0;
Изменил

2023-04-28 19:42 UTC, Alexstepano commented on Stepanov/KP7/src/Matrix.cpp
> +     int64_t  elem_from_div = 0;
Применил clang format - исправил +(вернул read me файл)

2023-04-29 08:52 UTC, Maxsmile123 requested changes

2023-04-29 08:52 UTC, Maxsmile123 commented on Stepanov/KP7/src/Matrix.cpp
> +    for (size_t y = 1; y < matrix_in_line.size(); y++) {
++y круче

2023-04-29 08:52 UTC, Maxsmile123 commented on Stepanov/KP7/src/Matrix.cpp
> +            if (!temp_vector[temp_vector.size() - 2]) {
Может, пояснить коммент

2023-04-29 08:52 UTC, Maxsmile123 commented on Stepanov/KP7/src/Matrix.cpp
> +void Matrix::divide(int64_t &cur_max_column, int64_t &max_elem)
Давай без булов, а рассматривать столбцы, ведь мы знаем их очерёдность

2023-04-29 08:52 UTC, Maxsmile123 commented on Stepanov/KP7/src/Matrix.cpp
> +void Matrix::print()
Тут тоже самое, давай упростим

2023-04-29 08:52 UTC, Maxsmile123 commented on Stepanov/KP7/src/Vector.cpp
> +            throw std::range_error("Too big accsesed memory");
Давай подумаем над текстом эксепшона

2023-04-29 08:52 UTC, Maxsmile123 commented on Stepanov/KP7/src/Vector.cpp
> +            throw std::range_error("Too big accsesed memory");
capacity overflow

2023-04-29 19:24 UTC, Alexstepano commented on Stepanov/KP7/src/Matrix.cpp
> +    for (size_t y = 1; y < matrix_in_line.size(); y++) {
Изменил

2023-04-29 19:26 UTC, Alexstepano commented on Stepanov/KP7/src/Matrix.cpp
> +            if (!temp_vector[temp_vector.size() - 2]) {
Все равно менял функцию, но этот if требуется в случае оставления индекса строки, что не содержит ненулевого элемента после операции деления.

2023-04-29 19:26 UTC, Alexstepano commented on Stepanov/KP7/src/Matrix.cpp
> +void Matrix::divide(int64_t &cur_max_column, int64_t &max_elem)
Изменил, теперь без bool

2023-04-29 19:27 UTC, Alexstepano commented on Stepanov/KP7/src/Vector.cpp
> +            throw std::range_error("Too big accsesed memory");
Изменил в 
[major vector changes]

2023-05-02 12:31 UTC, Maxsmile123 requested changes

2023-05-02 14:56 UTC, Alexstepano commented on Stepanov/KP7/tests/main.cpp
Ок, добавил тесты для конструкторов вектора

2023-05-02 18:44 UTC, Maxsmile123 approved these changes

2023-05-02 18:44 UTC, merged