23 Lab
Maxsmile123/MAI_109B_22 pull request #62
Opened 2023-04-25 18:50 UTC by BaronPipistron

2023-04-28 12:43 UTC, Maxsmile123 requested changes
Где обновление редмифайла с названием и вариантом?

2023-04-28 16:45 UTC, BaronPipistron commented
Добавил

2023-05-02 19:08 UTC, Maxsmile123 requested changes

2023-05-02 19:08 UTC, Maxsmile123 commented on Kontsebalov/lab23/src/BinaryTreeClass.cpp
> +    ++levels[level];
Выглядит страшно... Может, можно без массива обойтись? 
Если нет, то грустно... но что-то мне подсказывает, что можно (Вспомним алгоритм BFS...)

2023-05-02 19:08 UTC, Maxsmile123 commented on Kontsebalov/lab23/src/BinaryTreeClass.cpp
> +void BinaryTree<T>::visualizateTree(TreeNode<T>* root, int height){
А почему не захотел реализовать это в виде перегрузки оператора ```<<```?

2023-05-02 19:08 UTC, Maxsmile123 commented on Kontsebalov/lab23/src/TreeNodeClass.cpp
> +TreeNode<T>::TreeNode(T value){
Списки инициализации не любишь? :(

2023-05-02 19:08 UTC, Maxsmile123 commented on Kontsebalov/lab23/src/TreeNodeClass.cpp
> +TreeNode<T>::TreeNode(T value, TreeNode<T>* left, TreeNode<T>* right){
Списки инициализации? :((

2023-05-02 19:08 UTC, Maxsmile123 commented on Kontsebalov/lab23/tests/BinaryTree.cpp
> +int whatUserWant(){
Наверное, лучше по-другому назвать функцию ахахаха

2023-05-02 19:08 UTC, Maxsmile123 commented on Kontsebalov/lab23/tests/BinaryTree.cpp
> +int whatUserWant(){
Пользователь хочет спать

2023-05-02 19:08 UTC, Maxsmile123 commented on Kontsebalov/lab23/tests/BinaryTree.cpp
> +    std::cout << "Input the value of node (Remember about type!!!): ";
Если я напишу 3.5 - код сломается? Зачем мне помнить о типе? 
Тем более, это будет каждый раз выводиться, спамя мне в stdout

2023-05-02 19:08 UTC, Maxsmile123 commented on Kontsebalov/lab23/tests/BinaryTree.cpp
> +        tree.~BinaryTree();
Это очень зря... Явный вызов деструктора почти всегда неудачная идея. Может, просто сделать так, чтобы программа завершалась и деструктор вызывался бы сам, когда объект снимался бы со стека?

2023-05-02 19:08 UTC, Maxsmile123 commented on Kontsebalov/lab23/tests/BinaryTree.cpp
> +    while (true){
```
do{
   what_user_want = whatUserWant();
   doWhatUserWant(tree, what_user_want);
} while(what_user_want != 0) 
```

Наверное, лучше так

2023-05-02 19:08 UTC, Maxsmile123 commented on Kontsebalov/lab23/tests/BinaryTree.cpp
Название файла бы поменять... main.cpp или test.cpp или run.cpp

2023-05-13 21:28 UTC, closed without merging