Kp7 done
Maxsmile123/MAI_109B_22 pull request #63
Opened 2023-04-30 21:10 UTC by MeDGranD

Вариант: 1,11
Задание: Транспонировать матрицу относительно побочной диагонали. Проверить, является ли получившаяся матрица кососимметрической.

2023-05-07 13:21 UTC, Maxsmile123 requested changes
Вектор неэффективен

2023-05-07 13:21 UTC, Maxsmile123 commented on Lyubarsky/KP7/src/Vector.cpp
> +    this->resize(this->arraySize + 1, pushData);
Это неэффективно. У тебя push_back () работает за О(n)

2023-05-07 13:21 UTC, Maxsmile123 commented on Lyubarsky/KP7/src/Vector.cpp
> +        throw std::exception();
Зачем? Давай просто return делать

2023-05-07 13:21 UTC, Maxsmile123 commented on Lyubarsky/KP7/src/Vector.cpp
> +    this->resize(this->arraySize - 1);
resize работает за О(n), а нужно O(1)

2023-05-07 13:21 UTC, Maxsmile123 commented on Lyubarsky/KP7/src/Vector.cpp
> +        std::cout << "Incorrect vector index!" << std::endl;
Текст лучше сувать в конструктор исключения

2023-05-07 13:21 UTC, Maxsmile123 commented on Lyubarsky/KP7/src/Vector.cpp
> +    if ((index >= this->arraySize)||(index < 0)){
Чем это отличается от метода at? Погугли, чем они должны отличаться

2023-05-07 13:21 UTC, Maxsmile123 commented on Lyubarsky/KP7/src/Vector.cpp
> +        throw std::exception();
Не нужно лишний раз кидать исключения, это не круто

2023-05-07 13:21 UTC, Maxsmile123 commented on Lyubarsky/KP7/src/Vector.cpp
> +        throw std::exception();
Исключения нужно бросать тогда, когда возникает ситуация, при которой дальнейшее выполнение программы бессмысленно. Тут это не так

2023-05-07 13:21 UTC, Maxsmile123 commented on Lyubarsky/KP7/src/Vector.cpp
> +    if (this->arraySize == 0){
Тут тоже

2023-05-07 13:21 UTC, Maxsmile123 commented on Lyubarsky/KP7/src/Vector.cpp
> +    if (this->arraySize == 0) {
А просто вернуть это - нельзя?

2023-05-07 13:21 UTC, Maxsmile123 commented on Lyubarsky/KP7/src/Vector.cpp
> +    if (this->arraySize == 0){
Эта функция удаляет всё, что до size

2023-05-08 14:31 UTC, MeDGranD commented on Lyubarsky/KP7/include/Matrix.hpp
> +    Matrix(const std::string);
Поставил ссылку

2023-05-08 14:32 UTC, MeDGranD commented on Lyubarsky/KP7/src/Matrix.cpp
> +Matrix::Matrix(const std::string fileName){
Исправил

2023-05-08 14:35 UTC, MeDGranD commented on Lyubarsky/KP7/src/Matrix.cpp
> +        while(pointer != -1) {
можно заменить while на конструкцию if else. Но тогда семантика и кол-во действий не измениться (как было O(n), где n - последний ненулевой элемент строки, так и останется), а кол-во конструкций в коде увеличиться (вместо одного маленького while огромная конструкция if else)

2023-05-08 14:44 UTC, MeDGranD commented on Lyubarsky/KP7/src/Matrix.cpp
> +            while(pointer != -1){
В первом цикле метода я создаю m новых строк в новом векторе M. Дальше мне нужно обойти каждую строку и все элементы транспонировано вставить во второй новый массив A. Для этого я создаю цикл для каждой строки в старом массиве M (благо его размер легко узнать). А дальше возникают сложности с тем, что неизвестно, сколько ненулевых элементов в строке(точнее это можно узнать путем вычитания индексов соседних элементов из M и деления на 3, но это семантически очень усложняет код). Поэтому я завожу pointer, который в массиве A просматривает каждый отдельный элемент, пока не встретит -1 (т.е. конец данной строки).

2023-05-08 14:45 UTC, MeDGranD commented on Lyubarsky/KP7/include/Vector.hpp
> +    size_t arraySize;
Если назвать переменную size, тогда будет конфликт имен с именем метода size(), поэтому я решил изменить название на arraySize и соответственно на arrayCapacity, что, мне кажется, даже больше объясняет их область применения.

2023-05-08 14:47 UTC, MeDGranD commented on Lyubarsky/KP7/src/Vector.cpp
> +Vector<T>::Vector(const Vector<T>& otherVector): Vector(){
Метод resize изменит размер исходного вектора под входной(уменьшит или увеличит). А дальше произойдет копирование элементов из входного в исходный вектор.

2023-05-08 14:47 UTC, MeDGranD commented on Lyubarsky/KP7/src/Vector.cpp
> +    this->resize(this->arraySize + 1, pushData);
Признан эффективным за  O(1).

2023-05-08 14:48 UTC, MeDGranD commented on Lyubarsky/KP7/src/Vector.cpp
> +        throw std::exception();
Убрал пробрасывание исключения. Теперь просто делаю return.

2023-05-08 14:49 UTC, MeDGranD commented on Lyubarsky/KP7/src/Vector.cpp
> +        std::cout << "Incorrect vector index!" << std::endl;
Изменил вывод ошибок на конструкторы исключений.

2023-05-08 14:49 UTC, MeDGranD commented on Lyubarsky/KP7/src/Vector.cpp
> +    if ((index >= this->arraySize)||(index < 0)){
Метод at отличается от [] тем, что проверяет края вектора. Т.е. для [] эту проверку надо убрать.

2023-05-08 14:50 UTC, MeDGranD commented on Lyubarsky/KP7/src/Vector.cpp
> +        throw std::exception();
Убрал пробрасывание исключения.

2023-05-08 14:51 UTC, MeDGranD commented on Lyubarsky/KP7/src/Vector.cpp
> +    if (this->arraySize == 0){
Убрал пробрасывание исключения.

2023-05-08 18:57 UTC, Maxsmile123 requested changes
косметика

2023-05-08 18:57 UTC, Maxsmile123 commented on Lyubarsky/KP7/.vscode/c_cpp_properties.json
Это что-то явно лишнее

2023-05-09 08:02 UTC, MeDGranD commented on Lyubarsky/KP7/src/Vector.cpp
> +	this->Array = newArray;
убрал тут лишние пробелы

2023-05-09 08:03 UTC, MeDGranD commented on Lyubarsky/KP7/src/Vector.cpp
> +        while (newSize > this->arrayCapacity){
теперь делаю reservle на newSize * 2

2023-05-09 08:04 UTC, MeDGranD commented on Lyubarsky/KP7/.vscode/c_cpp_properties.json
удалил

2023-05-20 04:56 UTC, Maxsmile123 requested changes
Ты добавил сюда 23-ю лабу - это лишнее

2023-05-27 07:02 UTC, Maxsmile123 approved these changes

2023-05-27 07:02 UTC, merged