Efimenko Kirill lab 23 var 33 advanced
Maxsmile123/MAI_109B_22 pull request #64
Opened 2023-05-01 23:36 UTC by vivichv9

2023-05-03 17:00 UTC, Maxsmile123 commented on Efimenko/lab23/include/vector.hpp
> +        void pop(size_t index);
По спецификации у вектора такого метода нет 
https://en.cppreference.com/w/cpp/container/vector

2023-05-03 17:01 UTC, Maxsmile123 commented on Efimenko/lab23/include/vector.hpp
> +        void pop(size_t index);
Вероятно, ты имел ввиду erase, которые принимает два итератора(индекса), указывающие, какой промежуток нужно удалить

2023-05-03 17:01 UTC, Maxsmile123 commented on Efimenko/lab23/include/vector.hpp
> +        void pushBack(const T& data);
Где emplace_back()?

2023-05-03 17:02 UTC, Maxsmile123 commented on Efimenko/lab23/include/vector.hpp
> +        void popBack();
Го называть методы согласно спецификации - pop_back()

2023-05-03 17:02 UTC, Maxsmile123 commented on Efimenko/lab23/include/vector.hpp
> +        void pushBack(const T& data);
push_back

2023-05-03 17:02 UTC, Maxsmile123 commented on Efimenko/lab23/include/vector.hpp
> +        void shrinkToFit();
[shrink_to_fit](https://en.cppreference.com/w/cpp/container/vector/shrink_to_fit)

2023-05-03 17:03 UTC, Maxsmile123 commented on Efimenko/lab23/include/vector.hpp
> +        T at(size_t index);
А перегрузку оператора ```[]``` не сделаешь?

2023-05-03 17:04 UTC, Maxsmile123 commented on Efimenko/lab23/main.cpp
Это надо перенести в tests
+ нормально протестировать тут дерево (Вызвать у него все функции и проверить, что ты не словил утечку)

2023-05-03 17:04 UTC, Maxsmile123 commented on Efimenko/lab23/src/Node.cpp
> +Node<T>::Node(const T& data){
Списки инициализации тебе не нравятся? Почему? :(

2023-05-03 17:05 UTC, Maxsmile123 commented on Efimenko/lab23/src/Node.cpp
> +    leftNode = nullptr;
У тебя же это значения по умолчанию, это лишние строки

2023-05-03 17:05 UTC, Maxsmile123 commented on Efimenko/lab23/src/Node.cpp
> +T Node<T>::getData() {
Можно возвращать ссылку, ибо объект может быть большим - будет больно его копировать

2023-05-03 17:08 UTC, Maxsmile123 commented on Efimenko/lab23/src/Tree.cpp
> +    root = new Node<T>(data);
А сделать это в одну строчку нельзя?)
+ списки инициализации

2023-05-03 17:08 UTC, Maxsmile123 commented on Efimenko/lab23/src/Tree.cpp
> +    root = new Node<T>(NULL);
NULL - это СИ стайл, мы любим С++ - nullptr

2023-05-03 17:10 UTC, Maxsmile123 commented on Efimenko/lab23/src/Tree.cpp
> +        temp->setLeftNode(nullptr);
Ты сделал очень сложно - просто сделать дерево другом Ноды и убери эти методы страшные с установкой потомков

2023-05-03 17:10 UTC, Maxsmile123 commented on Efimenko/lab23/src/Tree.cpp
> +Node<T>* Tree<T>::insert(const T& data, Node<T>* temp) {
Почему название temp? Кажется, тут что-то другое подразумевается

2023-05-03 17:12 UTC, Maxsmile123 commented on Efimenko/lab23/src/Tree.cpp
> +        vec->pushBack(temp->getData());
Это похоже на дичь...Тебе же нужно кол-во (uint64_t), а не вектор...

2023-05-03 17:14 UTC, Maxsmile123 commented on Efimenko/lab23/src/vector.cpp
> +    T* newArray = new T(1);
А сразу присвоить нельзя? Зачем через переменную?

2023-05-03 17:14 UTC, Maxsmile123 commented on Efimenko/lab23/src/vector.cpp
> +    size = 0;
Значения по умолчанию?...

2023-05-03 17:15 UTC, Maxsmile123 commented on Efimenko/lab23/src/vector.cpp
> +Vector<T>::Vector(size_t capacity) {
Списки инициализации?... Значения по умолчанию?...

2023-05-03 17:16 UTC, Maxsmile123 commented on Efimenko/lab23/src/vector.cpp
> +    delete[] array;
Тут ты полчаешь UB и потенциальную утечку памяти

2023-05-03 17:16 UTC, Maxsmile123 commented on Efimenko/lab23/src/vector.cpp
> +    return size > 0 ? &array[size-1] : nullptr;
Пробелов бы добавить.... size -  1

2023-05-03 17:17 UTC, Maxsmile123 commented on Efimenko/lab23/src/vector.cpp
> +    if (capacity == size) reserve(2 * size);
Скобки потерял?

2023-05-03 17:18 UTC, Maxsmile123 commented on Efimenko/lab23/src/vector.cpp
> +    array[size].~T();
Сначала удалить, потом вызывать деструктор... Ты код то хоть тестировал? -_-

2023-05-03 17:19 UTC, Maxsmile123 commented on Efimenko/lab23/src/vector.cpp
> +void Vector<T>::push(size_t index, const T& data) {
insert... Зачем ты метод выставил, если он не реализован? Это вряд ли будет замержено в таком состоянии

2023-05-03 17:19 UTC, Maxsmile123 commented on Efimenko/lab23/src/vector.cpp
> +    delete[] reinterpret_cast<int8_t*>(array);
Привет UB и утечки

2023-05-03 17:20 UTC, Maxsmile123 commented on Efimenko/lab23/src/vector.cpp
> +    delete[] reinterpret_cast<int8_t*>(array);
+ метод неверно реализован - почитай, что делает оригинальный clear

2023-05-03 17:21 UTC, Maxsmile123 commented on Efimenko/lab23/src/vector.cpp
> +    return array[index];
Метод реализован неверно, почитай что он делает в спецификации и подумай, чем он отличается от []

2023-05-03 17:38 UTC, vivichv9 commented on Efimenko/lab23/Makefile
> +CXX       := clang++
поправлю

2023-05-03 17:45 UTC, vivichv9 commented on Efimenko/lab23/src/Tree.cpp
> +    root = new Node<T>(NULL);
в конструкторе полю data присваивается значение, если, например, будут лежать инты, то их же вроде нельзя объявить как nullptr

2023-05-03 17:46 UTC, vivichv9 commented on Efimenko/lab23/src/Tree.cpp
> +        temp->setLeftNode(nullptr);
переделаю

2023-05-03 17:47 UTC, vivichv9 commented on Efimenko/lab23/src/Tree.cpp
> +        vec->pushBack(temp->getData());
я все собираю в вектор, а потом вывожу его size.
и только сейчас понял, что можно просто счетчик))))

2023-05-03 17:51 UTC, vivichv9 commented on Efimenko/lab23/src/vector.cpp
> +    array[size].~T();
это правильно работает, индекс последнего элемента же на единицу меньше

2023-05-03 17:55 UTC, vivichv9 commented on Efimenko/lab23/src/vector.cpp
> +    delete[] array;
почему, delete[] же вызывает деструктор для каждого объекта в массиве, если в этом дело

2023-05-03 19:10 UTC, vivichv9 commented on Efimenko/lab23/src/vector.cpp
> +void Vector<T>::push(size_t index, const T& data) {
просто это же задание не про вектор, я пока написал методы, которые пригодятся здесь

2023-05-05 14:56 UTC, Maxsmile123 commented on Efimenko/lab23/src/Tree.cpp
> +    root = new Node<T>(NULL);
а, даже так. А я если я храню в дереве std::string - такие аругменты мне что выдадут?

2023-05-05 15:27 UTC, Maxsmile123 commented on Efimenko/lab23/src/vector.cpp
> +    array[size].~T();
Да, соре, я не прав. Но на утечки всё же проверь

2023-05-05 15:28 UTC, Maxsmile123 commented on Efimenko/lab23/src/vector.cpp
> +void Vector<T>::push(size_t index, const T& data) {
Лучше их тогда снести и в КП7 добавить

2023-05-08 19:01 UTC, Maxsmile123 requested changes

2023-05-08 19:01 UTC, Maxsmile123 commented on Efimenko/lab23/src/Tree.cpp
> +<<<<<<< Updated upstream
Интересно... Вангую, код не скомпилируется

2023-05-12 13:35 UTC, vivichv9 commented on Efimenko/lab23/src/Tree.cpp
> +<<<<<<< Updated upstream
какой-то прикол у вс кода, убрал

2023-05-12 13:36 UTC, vivichv9 commented on Efimenko/lab23/Makefile
заменил на нетронутый, сейчас должно быть норм

2023-05-12 13:37 UTC, vivichv9 commented on Efimenko/lab23/.DS_Store
удалил

2023-05-23 13:10 UTC, Maxsmile123 requested changes

2023-05-23 13:10 UTC, Maxsmile123 commented on Efimenko/lab23/src/vector.cpp
> +#include <algorithm>
Эту библиотеку использовать нельзя

2023-05-27 07:04 UTC, Maxsmile123 requested changes
Ты залили сюда ещё и КП6

2023-05-30 12:43 UTC, merged