Kp 8 stepanov
Maxsmile123/MAI_109B_22 pull request #67
Opened 2023-05-03 16:43 UTC by Alexstepano

Kp 8 , вариант 7,6,4, надеюсь, все будет ок

2023-05-04 21:03 UTC, Maxsmile123 requested changes
Я не смотрел реализацию списка - кажется, ты сделал кольцевой двунаправленный список с барьерным элементом - такого варианта нет :(
В остальном, всё очень хорошо, молодец!

2023-05-05 14:52 UTC, Maxsmile123 requested changes

2023-05-05 14:52 UTC, Maxsmile123 commented on Stepanov/KP8/src/List.cpp
> +    head->add_next(head);
Не, всё в порядке

2023-05-05 14:52 UTC, Maxsmile123 commented on Stepanov/KP8/include/List.hpp
> +    Node<T> *head;
Только у тебя это, по сути, не голова, а барьерный элемент. Давай переименуем?

2023-05-05 14:52 UTC, Maxsmile123 commented on Stepanov/KP8/src/List.cpp
> +size_t List<T>::get_size() const
Давай переименуем в size(), как в std::list

2023-05-05 14:52 UTC, Maxsmile123 commented on Stepanov/KP8/src/List.cpp
> +void List<T>::push_back()
А зачем эти два метода?...
Они же ничего не делают

2023-05-05 14:52 UTC, Maxsmile123 commented on Stepanov/KP8/src/List.cpp
> +    emplace_back(args...);
Но у тебя ведь нет такой реализации...Как оно компилируется вообще?

2023-05-05 14:52 UTC, Maxsmile123 commented on Stepanov/KP8/src/iterator.cpp
> +T Iterator<T>::fetch()
А почему не стал перегружать оператор ```*```?
Чтобы итератор вёл себя как указатель

2023-05-06 09:02 UTC, Alexstepano commented on Stepanov/KP8/include/List.hpp
> +    void lab_swap(const size_t &k);
Вообще нет,size_t будет меньше указателя за ссылкой весить(в 64-ой Ос). Убрал

2023-05-06 09:02 UTC, Alexstepano commented on Stepanov/KP8/include/Node.hpp
> +    void add_prev(Node *_prev);
Убрал в честь силы магии дружбы между классами(но вообще компилилось)

2023-05-06 09:02 UTC, Alexstepano commented on Stepanov/KP8/include/iterator.hpp
> +    void add_node(Node<T> *_node);
Согласен, необходимость данной функции отпала из-за дружбы

2023-05-06 09:03 UTC, Alexstepano commented on Stepanov/KP8/include/iterator.hpp
> +    void store(const T val);
вообще да, но store, как и fetch не нужны из-за того, что итератор теперь дружит с list

2023-05-06 09:03 UTC, Alexstepano commented on Stepanov/KP8/src/List.cpp
> +    sz = 0;
:(

2023-05-06 09:08 UTC, Alexstepano commented on Stepanov/KP8/src/Node.cpp
> +void Node<T>::add_next(Node<T> *_next)
Согласен, теперь list и iterator друзья node.(push_back ускорился в 4 раза)

2023-05-06 09:08 UTC, Alexstepano commented on Stepanov/KP8/src/iterator.cpp
> +        while (value && node) {
Изменил на то,как ты просил

2023-05-06 09:09 UTC, Alexstepano commented on Stepanov/KP8/include/List.hpp
> +    Node<T> *head;
Переименовал в barrier

2023-05-06 09:11 UTC, Alexstepano commented on Stepanov/KP8/src/List.cpp
> +void List<T>::push_back()
Про push_back согласен, он был лишним, а вот emlace_back у нас рассматривает вариант того, что вариативный шаблон к нам прийдет пустым(в том числе во время перебора прежнего непустого шаблона с помощью рекурсии перегружненной функции) - мы просто должны ничего не делать.

2023-05-06 09:12 UTC, Alexstepano commented on Stepanov/KP8/src/iterator.cpp
> +T Iterator<T>::fetch()
Согласен, изменил на оператор *

2023-05-06 09:13 UTC, Alexstepano commented on Stepanov/KP8/src/List.cpp
> +size_t List<T>::get_size() const
Переименовал

2023-05-06 09:26 UTC, Alexstepano commented on Stepanov/KP8/src/List.cpp
> +    emplace_back(args...);
https://learn.microsoft.com/ru-ru/cpp/cpp/ellipses-and-variadic-templates?view=msvc-160
Если коротко - вариативный шаблон(parameter pack)- шаблон, который представляет собой неопределенное количество введенных параметров.  При передаче в функцию они передаются как параметры через запятую(сonst T& A,сonst T& B и т.д.) Простого способа итерирования по этой структуре нет => я определяю функцию так, что первый пришедший элемент из parameter pack от него отделяется, push-ся в конец списка, после чего я рекурсивно повторяю вызов emplace back от уже оставшегося parameter pack без первого элемента=> беру его второй,если он присутствуют и push-ся в конец списка и т.д., пока у нас не останется пустой parameter pack, который при передачу в emplace_back активирует перегруженную версию этой функции, которая не принимает аргументов, что и завершит рекурсию. => все запушится и скомпилится

2023-05-08 19:07 UTC, Maxsmile123 approved these changes

2023-05-08 19:07 UTC, merged