Lab26 done!
Maxsmile123/MAI_109B_22 pull request #68
Opened 2023-05-06 16:58 UTC by MeDGranD

Вариант: 3,3
Задание: Реализовать структуру данных - дэк, а также определить конкатенацию двух дэков с последующей быстрой сортировкой.

2023-05-08 19:35 UTC, Maxsmile123 requested changes
Я не понял, зачем тебе чанки, если в задании сказано про массив

2023-05-08 19:35 UTC, Maxsmile123 commented on Lyubarsky/lab26/include/Deque.hpp
> +    deque<T> operator+(const deque<T>&) const;
Сложение дэков?)
Звучит странно

2023-05-08 19:35 UTC, Maxsmile123 commented on Lyubarsky/lab26/lib/Vector.cpp
Тут копипаста из КП7 - лучше давай сделаем инклуд вектора из папки с КП7

2023-05-08 19:35 UTC, Maxsmile123 commented on Lyubarsky/lab26/src/Deque.cpp
> +        this->array = reinterpret_cast<T*>(new char[sizeof(T)*6]);
А почему число 6? Магические непонятные константы - плохое дело. Обзови эту чиселку как-нибудь и вынести в константы в hpp дека

2023-05-08 19:35 UTC, Maxsmile123 commented on Lyubarsky/lab26/src/Deque.cpp
> +        for(size_t currentValue = 0; currentValue < 6; ++currentValue){
Тут тоже какая-то 6

2023-05-08 19:35 UTC, Maxsmile123 commented on Lyubarsky/lab26/src/Deque.cpp
> +    template<typename T>
Объявление шаблонов можно объединить(перечислить через запятую)

2023-05-08 19:35 UTC, Maxsmile123 commented on Lyubarsky/lab26/src/Deque.cpp
> +    T* chunk<T>::operator+(const Y plus) const{
Потенциально страшно складывать чанк с условным... списком или хэш-таблицей) 
Может, сделать специализацию шаблона с типами, которые ты предполагаешь будут использоваться? Так мы сможем ограничить пользователя

2023-05-08 19:35 UTC, Maxsmile123 commented on Lyubarsky/lab26/src/Deque.cpp
> +    T* chunk<T>::operator+(const Y plus) const{
И, кстати, ссылка потерялась(наверное)

2023-05-08 19:35 UTC, Maxsmile123 commented on Lyubarsky/lab26/src/Deque.cpp
> +        return currentDeque->chunks[this->currentIndex/6][this->currentIndex%6];
Ох уж эта 6

2023-05-08 19:35 UTC, Maxsmile123 commented on Lyubarsky/lab26/include/Deque.hpp
> +    Vector<Deque::chunk<T>> chunks;
Блин, слушай, аааам... Там нужно было делать дэк на массиве(пускай векторе), но не векторе массивов :(

2023-05-08 19:35 UTC, Maxsmile123 commented on Lyubarsky/lab26/src/Deque.cpp
> +        this->array = reinterpret_cast<T*>(new char[sizeof(T)*6]);
К тому же - нужна ли нам тут динамика, если мы знаем размер чанка?

2023-05-08 19:35 UTC, Maxsmile123 commented on Lyubarsky/lab26/src/Deque.cpp
> +        this->chunks.resize(this->chunks.size() *3 / 2);
Магические константы :(

2023-05-08 19:35 UTC, Maxsmile123 commented on Lyubarsky/lab26/src/Deque.cpp
> +        this->chunks.resize(this->chunks.size() *3 / 2);
Магические константы :(

2023-05-08 19:35 UTC, Maxsmile123 commented on Lyubarsky/lab26/src/Deque.cpp
> +size_t deque<T>::Size() const{
Лучше все методы писать либо с маленькой, либо с большой буквы. Переменную можно обозвать и по-другому(sz or _size)

2023-05-08 20:15 UTC, MeDGranD commented on Lyubarsky/lab26/src/Deque.cpp
> +        this->array = reinterpret_cast<T*>(new char[sizeof(T)*6]);
я использовал тут динамику для reinterpret_cast`a. Ведь мы можем хранить в деке динамические структуры (например динамические массивы) и не хотелось бы, что бы они сразу после создания чанка инициализировались в каждой его ячейке, тем самым засоряя память.

2023-05-11 10:30 UTC, MeDGranD commented on Lyubarsky/lab26/include/Deque.hpp
> +    deque<T> operator+(const deque<T>&) const;
Решил конкатенацию через этот оператор реализовать. Вроде по семантике больше всего подходит он.

2023-05-11 10:32 UTC, MeDGranD commented on Lyubarsky/lab26/src/Deque.cpp
> +        for(size_t currentValue = 0; currentValue < 6; ++currentValue){
Добавил константу dequeSize

2023-05-11 10:33 UTC, MeDGranD commented on Lyubarsky/lab26/src/Deque.cpp
> +    template<typename T>
Я пробовал, но компилятор требует, чтобы объявление шаблонов было точно таким же (в той же последовательности и в том же составе), как при объявлении метода.

2023-05-11 10:34 UTC, MeDGranD commented on Lyubarsky/lab26/src/Deque.cpp
> +    T* chunk<T>::operator+(const Y plus) const{
Заменил шаблон Y на size_t - семантика и результат сохранился.

2023-05-11 10:35 UTC, MeDGranD commented on Lyubarsky/lab26/include/Deque.hpp
> +    Vector<Deque::chunk<T>> chunks;
Но хотелось как лучше :(

2023-05-11 10:36 UTC, MeDGranD commented on Lyubarsky/lab26/src/Deque.cpp
> +        this->chunks.resize(this->chunks.size() *3 / 2);
Читал про то, что в отличие от вектора, дэк эффективнее будет увеличивать в 1.5 раза, т.к. с ним взаимодействие идет с двух сторон.

2023-05-11 10:37 UTC, MeDGranD commented on Lyubarsky/lab26/src/Deque.cpp
> +        this->chunks.resize(this->chunks.size() *3 / 2);
Читал про то, что в отличие от вектора, дэк эффективнее будет увеличивать в 1.5 раза, т.к. с ним взаимодействие идет с двух сторон.

2023-05-11 10:37 UTC, MeDGranD commented on Lyubarsky/lab26/src/Deque.cpp
> +size_t deque<T>::Size() const{
Изменил название метода на size, а название переменной на size_

2023-05-25 13:36 UTC, Maxsmile123 commented on Lyubarsky/lab26/include/Deque.hpp
> +    Vector<Deque::chunk<T>> chunks;
всё ок, договорились

2023-05-25 13:37 UTC, Maxsmile123 commented on Lyubarsky/lab26/src/Deque.cpp
> +        return currentDeque->chunks[this->currentIndex/6][this->currentIndex%6];
А это разве размер дэка? Не размер батча(а.к.а. чанка?)

2023-05-25 13:38 UTC, Maxsmile123 commented on Lyubarsky/lab26/src/Deque.cpp
> +    template<typename T>
И в чём проблема так сделать?

2023-05-25 13:39 UTC, Maxsmile123 commented on Lyubarsky/lab26/src/Deque.cpp
> +        this->array = reinterpret_cast<T*>(new char[sizeof(T)*6]);
Разумно

2023-05-30 00:05 UTC, Maxsmile123 approved these changes

2023-05-30 00:07 UTC, merged