nothing to see here, just little bug fix
Maxsmile123/MAI_109B_22 pull request #69
Opened 2023-05-06 17:56 UTC by Alexstepano

just little bug fix

2023-05-06 18:17 UTC, Maxsmile123 requested changes

2023-05-06 18:17 UTC, Maxsmile123 commented on Stepanov/KP7/src/Vector.cpp
> +void Vector<T>::emplace_back()
Это зачем?

2023-05-06 18:35 UTC, Alexstepano commented on Stepanov/KP7/src/Vector.cpp
> +void Vector<T>::emplace_back()
emlace_back у нас рассматривает вариант того, что вариативный шаблон к нам прийдет пустым(в том числе во время перебора прежнего непустого шаблона с помощью рекурсии перегружненной функции) - мы просто должны ничего не делать.

2023-05-08 18:51 UTC, Maxsmile123 approved these changes

2023-05-08 18:51 UTC, merged