Kp8 variant 11, 6, 7 Huan advanced
Maxsmile123/MAI_109B_22 pull request #74
Opened 2023-05-17 19:30 UTC by tng00

Обработка линейного двунаправленного списка с барьерным элементом. Тип хранимых данных - ссылочный. Нестандартное действие: удалить элементы списка, имеющие значения, находящиеся в заданном диапазоне.

Случайно сначала сделал другой вариант (реверс списка), не стал убирать.

2023-05-26 07:30 UTC, Maxsmile123 requested changes

2023-05-26 07:30 UTC, Maxsmile123 commented on Huan/KP8/src/List.cpp
> +  Iterator<T> temp(barrier_->next_);
Может, лучше хранить в списке итератор на барьерный элемент? Тогда не придётся каждый раз копии делать

2023-05-26 07:30 UTC, Maxsmile123 commented on Huan/KP8/src/List.cpp
> +  Iterator<T> temp(barrier_);
Аналогично

2023-05-26 07:30 UTC, Maxsmile123 commented on Huan/KP8/src/List.cpp
> +  Iterator<T> first = this->begin();
Ну ты понял про итераторы, дальше по коду замечания те же

2023-06-03 10:10 UTC, tng00 commented on Huan/KP8/src/List.cpp
> +void List<T>::emplace_back(const T &first, const Args &...args) {
пофиксил

2023-06-03 10:10 UTC, tng00 commented on Huan/KP8/src/List.cpp
> +  T temp_value = value;
реально

2023-06-03 10:21 UTC, tng00 commented on Huan/KP8/src/Iterator.cpp
> +      if (node_) {
не, он нужен чтобы знать де- или инкрементировать num, а также переходить к следующему или предыдущему элементу

2023-06-03 10:23 UTC, tng00 commented on Huan/KP8/src/Iterator.cpp
> +      if (node_) {
пофиксил

2023-06-03 10:23 UTC, tng00 commented on Huan/KP8/src/Iterator.cpp
> +      if (node_) {
пофиксил

2023-06-03 10:24 UTC, tng00 commented on Huan/KP8/src/List.cpp
> +  barrier_ = nullptr;
пофиксил

2023-06-03 13:22 UTC, tng00 commented on Huan/KP8/src/List.cpp
> +  Iterator<T> temp(barrier_->next_);
пофиксил

2023-06-03 13:22 UTC, tng00 commented on Huan/KP8/src/List.cpp
> +  Iterator<T> temp(barrier_);
пофиксил

2023-06-03 13:23 UTC, tng00 commented on Huan/KP8/src/List.cpp
> +  Iterator<T> first = this->begin();
пофиксил

2023-06-03 13:27 UTC, tng00 commented on Huan/KP8/src/List.cpp
> +bool List<T>::find(Iterator<T> first, Iterator<T> last, const T &value) const {
сделал так, только вместо нулевого end

2023-06-05 09:55 UTC, Maxsmile123 requested changes

2023-06-05 09:55 UTC, Maxsmile123 commented on Huan/KP8/src/List.cpp
> +  T temp_value = value;
Кажется, это тоже лишнее

2023-06-05 09:55 UTC, Maxsmile123 commented on Huan/KP8/src/List.cpp
> +void List<T>::emplace_back(const T &first, const Args &...args) {
Ладно, видимо, это стоит скипнуть

2023-06-05 14:17 UTC, tng00 commented on Huan/KP8/src/List.cpp
> +  T temp_value = value;
действительно. пофиксил

2023-06-05 21:22 UTC, tng00 commented on Huan/KP8/src/List.cpp
> +void List<T>::emplace_back(const T &first, const Args &...args) {
Убрать то есть?

2023-06-06 10:36 UTC, Maxsmile123 commented on Huan/KP8/src/List.cpp
> +void List<T>::emplace_back(const T &first, const Args &...args) {
Не, просто чёт не разобрались, как работает emplace_back. Это не верная реализация, но да ладно

2023-06-06 10:40 UTC, Maxsmile123 approved these changes

2023-06-06 10:40 UTC, merged