Stepanov_21 lab_ adv
Maxsmile123/MAI_109B_22 pull request #8
Opened 2023-02-26 10:51 UTC by Alexstepano

21 лабораторная работа, 22 вариант, я не знаю, существует ли кодстайл в Python, но я попытался код в nano максимально привести к читаемому виду. Жду конструктивной критики, если таковая присутствует.

2023-02-26 15:27 UTC, Maxsmile123 requested changes
Кодстайл. Лучше установи себе текстовый редактор VS code

2023-02-26 15:27 UTC, Maxsmile123 commented on Stepanov/lab21/python_script.py
> +def Parser_setup():
Приведи код к единственному кодстайлу в Python - PEP8

2023-02-26 15:27 UTC, Maxsmile123 commented on Stepanov/lab21/python_script.py
> +def Name_changer(size,path):
Название функций принято писать с маленькой буквы

2023-02-26 15:27 UTC, Maxsmile123 commented on Stepanov/lab21/python_script.py
> +    for paath, dirs, files in os.walk(path):
```paath``` - явная опечатка

2023-02-26 15:27 UTC, Maxsmile123 commented on Stepanov/lab21/python_script.py
> +            new_file = os.path.join(paath, file[: file.find(".") + 1] + file[0:1])
Второй аргумент стоит сделать проще - сейчас это выглядит непонятно и заставляет долго сидеть и понимать, что происходит

2023-02-26 15:27 UTC, Maxsmile123 commented on Stepanov/lab21/python_script.py
> +    size=Parser_setup()
Странное название функции - Parser нельзя установить, вроде

2023-02-26 15:27 UTC, Maxsmile123 commented on Stepanov/lab21/python_script.py
> +    path="./"
Это лучше вынести в константы

2023-02-26 15:27 UTC, Maxsmile123 commented on Stepanov/lab21/bash_script.sh
> +             file_name=$(echo $file|rev|cut -d '/' -f1|rev)
Сюдя явно забыли добавить пробелов - пройдись по всему скрипту и проверь, чтобы никто не клеился к |

2023-02-27 16:55 UTC, Alexstepano commented on Stepanov/lab21/python_script.py
> +def Name_changer(size,path):
Исправил, теперь она обозначается как name_changer()

2023-02-27 16:55 UTC, Alexstepano commented on Stepanov/lab21/python_script.py
> +    for paath, dirs, files in os.walk(path):
Исправил всюду код на path

2023-02-27 16:57 UTC, Alexstepano commented on Stepanov/lab21/python_script.py
> +    size=Parser_setup()
:(. Ну ладно, переименовал в parser_get_size()

2023-02-27 16:58 UTC, Alexstepano commented on Stepanov/lab21/python_script.py
> +    path="./"
Указал, что переменная является константой(CONST_PATH)

2023-02-27 16:59 UTC, Alexstepano commented on Stepanov/lab21/python_script.py
> +def Parser_setup():
Сделано, я старался

2023-02-28 00:45 UTC, Maxsmile123 requested changes
Учимся писать код

2023-02-28 00:45 UTC, Maxsmile123 commented on Stepanov/lab21/python_script.py
> +def parser_get_size():
КМК, лучше назвать функцию get_arguments. С текущем названием проблемы при масштабировании - что если ты захочешь добавить ещё один аргумент? Тогда название нужно будет менять, что уже звучит ненадёжно

2023-02-28 00:45 UTC, Maxsmile123 commented on Stepanov/lab21/python_script.py
> +        "size",
Вообще, принято указывать полный аргумент и сокращённый. Посмотри в документации, как это делается для данной функции

2023-02-28 00:45 UTC, Maxsmile123 commented on Stepanov/lab21/python_script.py
> +def name_changer(size, path):
А давай будем использовать аннотации типов. Чтобы было понятно, что за тип у переменных. Погугли, как это делается

2023-02-28 00:45 UTC, Maxsmile123 commented on Stepanov/lab21/python_script.py
> +            not_an_abs_path = os.path.join(path, file)
Название плохое - я не понимаю, что означает эта переменная

2023-02-28 00:45 UTC, Maxsmile123 commented on Stepanov/lab21/python_script.py
> +            if size >= filesize:
Давай придумаем название получше абстрактного ```size```

2023-02-28 00:45 UTC, Maxsmile123 commented on Stepanov/lab21/python_script.py
> +                file_preff = file[: file.find(".") + 1]
Может, не будем экономить на символах и сделаем file_prefix? Так ведь намного удобнее читать

2023-02-28 00:45 UTC, Maxsmile123 commented on Stepanov/lab21/python_script.py
> +                file_first_char = file[0:1]
А зачем срез? Это же можно сделать как file[0]

2023-02-28 00:45 UTC, Maxsmile123 commented on Stepanov/lab21/python_script.py
> +    CONST_PATH = "./"
Это не совсем то, что я имел ввиду. Нужно было вынести её как глобальную переменную и объявить сверху. А лучше давай запрашивать путь у пользователя - логика скрипта особо не поменяется, а функциональности станет больше

2023-02-28 00:45 UTC, Maxsmile123 commented on Stepanov/lab21/bash_script.sh
> +	echo "Pleace,insert exactly 1 argument -size"
Давай соблюдать правила написания английских слов и делать пробелы после запятых

2023-02-28 00:45 UTC, Maxsmile123 commented on Stepanov/lab21/bash_script.sh
> +        echo ". [scriptname].sh [size]"
А давай сделаем функциональность по типу:
```[scrtptname].sh -s [size]```
Вместо -s можно писать и просто --size. Посмотри, как это можно сделать в Баш и проделай то же самое в пайтон

2023-02-28 00:45 UTC, Maxsmile123 commented on Stepanov/lab21/bash_script.sh
> +             file_suff=$(echo $file | rev | cut -d '.' -f1 | rev)
file_suffix - не экономь на чернилах)

2023-02-28 00:45 UTC, Maxsmile123 commented on Stepanov/lab21/bash_script.sh
> +             size_of_suf=$(echo $file_suff | wc -c)
size_of_suffix

2023-02-28 00:45 UTC, Maxsmile123 commented on Stepanov/lab21/bash_script.sh
> +             pref_file=$(echo $file_name | rev | cut -c $size_of_suf- | rev)
file_prefix

2023-02-28 00:45 UTC, Maxsmile123 commented on Stepanov/lab21/bash_script.sh
> +             fl=$(echo $file_name | cut -c 1)
```fl```?  Я не понимаю, что означает эта переменная

2023-02-28 00:45 UTC, Maxsmile123 commented on Stepanov/lab21/bash_script.sh
> +             not_an_abs_path=$(echo $file | rev | cut -c  $size_of_file-  | rev)
Я не понимаю, что это означает. Давай найдём название для функции получше

2023-02-28 09:22 UTC, Alexstepano commented on Stepanov/lab21/python_script.py
> +def parser_get_size():
Переменовал в parser_get_arguments.

2023-02-28 09:24 UTC, Alexstepano commented on Stepanov/lab21/python_script.py
> +        "size",
Я надеюсь, что правильно понял и обновил объявление каждого из аргументов, добавив флаги -s и --size к первому, а также -pr и --relative_path  ко второму

2023-02-28 09:25 UTC, Alexstepano commented on Stepanov/lab21/python_script.py
> +def name_changer(size, path):
изменил, теперь явно объявлено, что maximum_size_for_find : integer, а  path: string

2023-02-28 09:25 UTC, Alexstepano commented on Stepanov/lab21/python_script.py
> +            not_an_abs_path = os.path.join(path, file)
Исправил на relative_path

2023-02-28 09:26 UTC, Alexstepano commented on Stepanov/lab21/python_script.py
> +            if size >= filesize:
maximum_size_for_find пойдет?

2023-02-28 09:26 UTC, Alexstepano commented on Stepanov/lab21/python_script.py
> +                file_preff = file[: file.find(".") + 1]
а как же 6 долларов? Исправил

2023-02-28 09:27 UTC, Alexstepano commented on Stepanov/lab21/python_script.py
> +                file_first_char = file[0:1]
Ок, исправил без среза

2023-02-28 09:29 UTC, Alexstepano commented on Stepanov/lab21/python_script.py
> +    CONST_PATH = "./"
Переписал, добавив аргумент relative_path, который дополнительно запрашивается у пользователя

2023-02-28 09:32 UTC, Alexstepano commented on Stepanov/lab21/bash_script.sh
> +             fl=$(echo $file_name | cut -c 1)
first_char_of_file

2023-02-28 09:32 UTC, Alexstepano commented on Stepanov/lab21/bash_script.sh
> +             not_an_abs_path=$(echo $file | rev | cut -c  $size_of_file-  | rev)
изменил на relative_path

2023-02-28 10:17 UTC, Alexstepano commented on Stepanov/lab21/bash_script.sh
> +	echo "Pleace,insert exactly 1 argument -size"
Ок, поменял

2023-02-28 10:29 UTC, Alexstepano commented on Stepanov/lab21/bash_script.sh
> +        echo ". [scriptname].sh [size]"
Обновил функционал, посоветовашись с уже сдавшими

2023-02-28 11:26 UTC, Maxsmile123 requested changes
Пробелы наше всё

2023-02-28 11:26 UTC, Maxsmile123 commented on Stepanov/lab21/bash_script.sh
> +	echo "Pleace , insert exactly argument with flag -s or --size: -s [SIZE]"
Please... not pleace

2023-02-28 11:26 UTC, Maxsmile123 commented on Stepanov/lab21/bash_script.sh
> +elif [[ $2 = '?' ]]
А ты не проверяешь первый аргумент? Т.е. я могу написать первым аргумент любой текст - он его воспримет как верный, что неправильно. 
Пример: я могу делать так:
``` ./run.sh --lol 5```
И это будет работать также как:
```./run.sh -s 5```

2023-02-28 11:26 UTC, Maxsmile123 commented on Stepanov/lab21/python_script.py
> +    return args.size,args.relative_path
Пробел после запятой

2023-02-28 11:26 UTC, Maxsmile123 commented on Stepanov/lab21/python_script.py
> +def name_changer(maximum_size_for_find : int, path: str):
Т.е. я могу задать отрицательный размер? Что тогда будет?

2023-02-28 11:26 UTC, Maxsmile123 commented on Stepanov/lab21/python_script.py
> +    size,relative_path = parser_get_arguments()
Пробелы...

2023-02-28 18:58 UTC, Alexstepano commented on Stepanov/lab21/python_script.py
> +    return args.size,args.relative_path
Добавил

2023-02-28 18:58 UTC, Alexstepano commented on Stepanov/lab21/python_script.py
> +    size,relative_path = parser_get_arguments()
Empty spaces - what are we living for?
Abandoned places - I guess we know the score..
On and on!
Does anybody know what we are looking for?

2023-02-28 19:09 UTC, Alexstepano commented on Stepanov/lab21/python_script.py
> +def name_changer(maximum_size_for_find : int, path: str):
Да, скрипт тогда будет искать файлы меньше отрицательного размера(то есть идти по всем файлам, получая их размеры и сравнивая с заданным числом),но ничего не найдет, ибо минимальный размер(как я думаю) существующего файла равен 0.
Вот доказательство того, что ничего страшного при отрицательном аргументе maximum_size_for_find не случается

2023-02-28 19:10 UTC, Alexstepano commented on Stepanov/lab21/python_script.py
> +def name_changer(maximum_size_for_find : int, path: str):
alex@alex-VirtualBox:~$ ls -l
total 60
-rw-rw-r-- 1 alex alex    0 фев 23 18:32 '*.1'
-rw-rw-r-- 1 alex alex 1077 фев 26 12:32  bashi.sh
-rw-rw-r-- 1 alex alex 1080 фев 23 18:31  bfbfbfbf.sh
drwxr-xr-x 2 alex alex 4096 фев 23 17:42  Desktop
drwxr-xr-x 2 alex alex 4096 фев 23 17:42  Documents
drwxr-xr-x 2 alex alex 4096 фев 28 12:05  Downloads
-rw-rw-r-- 1 alex alex  656 фев 24 14:53  its-work.py
drwxrwxr-x 2 alex alex 4096 фев 28 13:23  Mus
drwxr-xr-x 2 alex alex 4096 фев 24 14:53  Music
drwxr-xr-x 2 alex alex 4096 фев 23 17:42  Pictures
drwxr-xr-x 2 alex alex 4096 фев 23 17:42  Public
drwx------ 4 alex alex 4096 фев 23 18:09  snap
-rw-rw-r-- 1 alex alex  146 фев 23 19:45  sol.sh
-rw-rw-r-- 1 alex alex  366 фев 23 21:43  solution.sh
drwxr-xr-x 2 alex alex 4096 фев 23 17:42  Templates
drwxr-xr-x 2 alex alex 4096 фев 24 14:54  Videos
alex@alex-VirtualBox:~$ rm -r Mus
alex@alex-VirtualBox:~$ mkdir Mus
alex@alex-VirtualBox:~$ cd Mus
alex@alex-VirtualBox:~/Mus$ ls -l
total 0
alex@alex-VirtualBox:~/Mus$ touch 1{22..33}.i_dont_wanna_die
alex@alex-VirtualBox:~/Mus$ nano python_script.py
alex@alex-VirtualBox:~/Mus$ python3 python_script.py -s -100 -rp ./
Done
alex@alex-VirtualBox:~/Mus$ ls -l
total 4
-rw-rw-r-- 1 alex alex    0 фев 28 22:02 122.i_dont_wanna_die
-rw-rw-r-- 1 alex alex    0 фев 28 22:02 123.i_dont_wanna_die
-rw-rw-r-- 1 alex alex    0 фев 28 22:02 124.i_dont_wanna_die
-rw-rw-r-- 1 alex alex    0 фев 28 22:02 125.i_dont_wanna_die
-rw-rw-r-- 1 alex alex    0 фев 28 22:02 126.i_dont_wanna_die
-rw-rw-r-- 1 alex alex    0 фев 28 22:02 127.i_dont_wanna_die
-rw-rw-r-- 1 alex alex    0 фев 28 22:02 128.i_dont_wanna_die
-rw-rw-r-- 1 alex alex    0 фев 28 22:02 129.i_dont_wanna_die
-rw-rw-r-- 1 alex alex    0 фев 28 22:02 130.i_dont_wanna_die
-rw-rw-r-- 1 alex alex    0 фев 28 22:02 131.i_dont_wanna_die
-rw-rw-r-- 1 alex alex    0 фев 28 22:02 132.i_dont_wanna_die
-rw-rw-r-- 1 alex alex    0 фев 28 22:02 133.i_dont_wanna_die
-rw-rw-r-- 1 alex alex 1564 фев 28 22:03 python_script.py
alex@alex-VirtualBox:~/Mus$ python3 python_script.py -s 100 -rp ./
Done
alex@alex-VirtualBox:~/Mus$ ls -l
total 4
-rw-rw-r-- 1 alex alex    0 фев 28 22:02 122.1
-rw-rw-r-- 1 alex alex    0 фев 28 22:02 123.1
-rw-rw-r-- 1 alex alex    0 фев 28 22:02 124.1
-rw-rw-r-- 1 alex alex    0 фев 28 22:02 125.1
-rw-rw-r-- 1 alex alex    0 фев 28 22:02 126.1
-rw-rw-r-- 1 alex alex    0 фев 28 22:02 127.1
-rw-rw-r-- 1 alex alex    0 фев 28 22:02 128.1
-rw-rw-r-- 1 alex alex    0 фев 28 22:02 129.1
-rw-rw-r-- 1 alex alex    0 фев 28 22:02 130.1
-rw-rw-r-- 1 alex alex    0 фев 28 22:02 131.1
-rw-rw-r-- 1 alex alex    0 фев 28 22:02 132.1
-rw-rw-r-- 1 alex alex    0 фев 28 22:02 133.1
-rw-rw-r-- 1 alex alex 1564 фев 28 22:03 python_script.py
alex@alex-VirtualBox:~/Mus$ cat python_script.py
import argparse
import os
 
 
def parser_get_arguments():
    parser = argparse.ArgumentParser(
        description = "this script implements a replacement \
        for all files in the \
        directory with a size less than\
        the specified postfix\
        by the first character \
        of the file name"
     )
    parser.add_argument(
        "-s",
        "--size",
        required = True,
        type = int,
        action = "store",
        help = "max size of files \
        in current directory\
        to consider them \
        suitable",
     )
    parser.add_argument(
        "-rp",
        "--relative_path",
        required = True,
        type = str,
        action = "store",
        help = "path to the directory,\
        where user want to\
        use this python script",
     )
    args = parser.parse_args()
    return args.size, args.relative_path
 
 
def name_changer(maximum_size_for_find : int, path: str):
    for path, dirs, files in os.walk(path):
        for file in files:
            relative_path = os.path.join(path, file)
            filesize = os.path.getsize(relative_path)
            if maximum_size_for_find >= filesize:
                file_prefix = file[: file.find(".") + 1]
                file_first_char = file[0]
                new_file = os.path.join(path, file_prefix + file_first_char)
                os.rename(relative_path, new_file)
 
 
def main():
    size, relative_path = parser_get_arguments()
    name_changer(size, relative_path)
    print("Done")
 
 
if __name__ == "__main__":
    main()
alex@alex-VirtualBox:~/Mus$

2023-02-28 19:13 UTC, Alexstepano commented on Stepanov/lab21/python_script.py
> +def name_changer(maximum_size_for_find : int, path: str):
$test$

2023-02-28 19:50 UTC, Alexstepano commented on Stepanov/lab21/bash_script.sh
> +	echo "Pleace , insert exactly argument with flag -s or --size: -s [SIZE]"
ok, i have already changed it

2023-02-28 19:51 UTC, Alexstepano commented on Stepanov/lab21/bash_script.sh
> +elif [[ $2 = '?' ]]
я дописал условий, теперь все должно быть ок

2023-02-28 22:02 UTC, Maxsmile123 approved these changes

2023-02-28 22:02 UTC, Maxsmile123 commented on Stepanov/lab21/python_script.py
> +def name_changer(maximum_size_for_find : int, path: str):
Тут бы приклеить : к название переменной, но да ладно

2023-02-28 22:03 UTC, merged