Kp 9 stepanov
Maxsmile123/MAI_109B_22 pull request #89
Opened 2023-05-26 16:29 UTC by Alexstepano

Вариант №: <8,3>
Задание: <Метод сортировки:Турнирная сортировка,тип ключа:строковый,хранение отдельно от данных>
Надеюсь, что все будет ок.

2023-05-27 09:36 UTC, Maxsmile123 requested changes

2023-05-27 09:36 UTC, Maxsmile123 commented on Stepanov/KP9/include/tournament_sort.hpp
Это должен быть метод

2023-05-27 09:36 UTC, Maxsmile123 commented on Stepanov/KP9/src/Table.cpp
Поехало

2023-05-27 09:43 UTC, Maxsmile123 requested changes

2023-05-27 09:43 UTC, Maxsmile123 commented on Stepanov/KP9/src/Table.cpp
> +void Table<T>::print(){
Убери

2023-05-27 09:43 UTC, Maxsmile123 commented on Stepanov/KP9/src/Table.cpp
> +   return "";
Замени на это https://en.cppreference.com/w/cpp/string/basic_string/npos

2023-05-27 09:43 UTC, Maxsmile123 commented on Stepanov/KP9/src/tournament_sort.cpp
> +        if(i%2==0&&i<2*n-1){
Оставь коммент

2023-05-27 16:09 UTC, Alexstepano commented on Stepanov/KP9/include/tournament_sort.hpp
Изменил, теперь это статический метод

2023-05-27 16:09 UTC, Alexstepano commented on Stepanov/KP9/src/Table.cpp
Исправил

2023-05-27 16:09 UTC, Alexstepano commented on Stepanov/KP9/src/Table.cpp
> +void Table<T>::print(){
Убрал за ненужностью

2023-05-27 16:11 UTC, Alexstepano commented on Stepanov/KP9/src/tournament_sort.cpp
> +        if(i%2==0&&i<2*n-1){
Оставил, должно быть более понятен принцип выбора "соперника"

2023-05-27 16:12 UTC, Alexstepano commented on Stepanov/KP9/src/Table.cpp
> +   return "";
npos - const size_t, его вернуть нельзя в поиске, где мы возвращаем строку по ключу.

2023-05-30 00:35 UTC, Maxsmile123 requested changes

2023-05-30 00:35 UTC, Maxsmile123 commented on Stepanov/KP9/include/Table.hpp
> +    Table sort(const T &inf);
А сортировка может возвращать void? Лучше сделать void

2023-05-30 00:35 UTC, Maxsmile123 commented on Stepanov/KP9/include/Table.hpp
> +    void insert_in_back(const T &key, const std::string &input_data);
a.k.a. push_back()?

2023-05-30 00:35 UTC, Maxsmile123 commented on Stepanov/KP9/tests/main.cpp
> +const int INF = 1e5;
```std::numeric_limits<int>::max()```?

2023-05-31 11:46 UTC, Alexstepano commented on Stepanov/KP9/tests/main.cpp
> +const int INF = 1e5;
Забыл ранее убрать из мейна, использовал для тестов.

2023-05-31 11:46 UTC, Alexstepano commented on Stepanov/KP9/tests/main.cpp
> +const int INF = 1e5;
Убрал

2023-05-31 11:46 UTC, Alexstepano commented on Stepanov/KP9/include/Table.hpp
> +    void insert_in_back(const T &key, const std::string &input_data);
Переименовал

2023-05-31 11:46 UTC, Alexstepano commented on Stepanov/KP9/include/Table.hpp
> +    Table sort(const T &inf);
Сделал

2023-05-31 17:09 UTC, Maxsmile123 approved these changes

2023-05-31 17:09 UTC, merged