lab23 fomin var21
Maxsmile123/MAI_109B_22 pull request #90
Opened 2023-05-26 16:53 UTC by Haliava

2023-05-30 00:47 UTC, Maxsmile123 requested changes
Приведи код в порядок - у тебя куча лишних файлов, я не понимаю, куда смотреть

2023-05-30 00:47 UTC, Maxsmile123 commented on Fomin/lab23/include/Node.hpp
> +#include <algorithm>
Это использовать нельзя

2023-05-30 00:47 UTC, Maxsmile123 commented on Fomin/lab23/include/Tree.h
> +
Нет функции поиска

2023-05-30 00:47 UTC, Maxsmile123 commented on Fomin/lab23/include/Tree.h
> +    int getDepthOfSmallestNode();
smallest лучше заменить на minimum

2023-05-30 00:47 UTC, Maxsmile123 commented on Fomin/lab23/include/Tree.h
> +    void print(const std::string& prefix, Node<T>* parent, bool isLeft, bool isRoot);
Лучше ещё написать перегрузку этой функции, которая вызывается без параметров - пользователь хочет просто распечатать текущее дерево, ему не нужно знать про какого-то родителя и булевские переменные ( к слову, они тоже лишние)

2023-05-30 00:47 UTC, Maxsmile123 commented on Fomin/lab23/include/Tree.h
Стоп, а как это вообще скопилируется, если это .h? В Си нет классов

2023-05-30 00:47 UTC, Maxsmile123 commented on Fomin/lab23/include/Node.h
У нас С++, не Си

2023-05-30 06:31 UTC, Haliava commented on Fomin/lab23/include/Node.h
можно писать и h, и hpp. Вот, например проект на плюсах, но там тоже используется h.
https://github.com/dolphin-emu/dolphin/tree/master/Source/Core/Common

2023-05-30 14:54 UTC, Maxsmile123 commented on Fomin/lab23/include/Node.h
Хорошо, но тогда объясни зачем тебе это понадобилось?

2023-05-30 14:54 UTC, Maxsmile123 commented on Fomin/lab23/include/Node.h
И выбери что-то одно: .h или .hpp

2023-05-30 15:09 UTC, Haliava commented on Fomin/lab23/include/Node.h
Это я загрузил файлы с новым решением (с  расширениями .h) в папку со старым решением (с расширениями .hpp). Вооот они не перезаписались, а просто рядом закинулись. Я старые файлы удалю с новым коммитом

2023-05-30 15:43 UTC, Haliava commented on Fomin/lab23/include/Tree.h
> +
Какого поиска? То есть сказать, есть нода в дереве или нет? Просто такого задания я не вижу

2023-06-01 18:48 UTC, Haliava commented on Fomin/lab23/include/Node.hpp
> +#include <algorithm>
убрал

2023-06-01 18:48 UTC, Haliava commented on Fomin/lab23/include/Tree.h
> +    int getDepthOfSmallestNode();
поменял

2023-06-05 20:39 UTC, Maxsmile123 commented on Fomin/lab23/include/Tree.h
> +
Поиск элемента в дереве. По класске структуры оценивают по трём операциям: поиск, вставка и удаление. Хочется видеть именно поиск элемента. Можно в виде ```bool find(const& T val);```

2023-06-05 20:39 UTC, Maxsmile123 requested changes
Добавил коммент по поводу поиска

2023-06-07 18:31 UTC, Haliava commented on Fomin/lab23/include/Tree.h
> +
сделал

2023-06-07 18:33 UTC, Haliava commented
сделал

2023-06-07 18:49 UTC, merged